"""MARC 21 Bibliographic and Authority standards, tags, indicator codes, and constants.

Defines standard tags, leader offsets, subfield delimiters, country codes,
language codes, control field character maps, and bibliographic level definitions.
"""

from typing import Dict, Set, List, Tuple

# Leader constants
LEADER_LENGTH = 24
RECORD_STATUS_INCREASE_IN_ENCODING = "a"
RECORD_STATUS_CORRECTED_OR_REVISED = "c"
RECORD_STATUS_DELETED = "d"
RECORD_STATUS_NEW = "n"
RECORD_STATUS_PREVIOUS_RECORD = "p"

RECORD_TYPE_LANGUAGE_MATERIAL = "a"
RECORD_TYPE_NOTATED_MUSIC = "c"
RECORD_TYPE_MANUSCRIPT_MUSIC = "d"
RECORD_TYPE_CARTOGRAPHIC_MATERIAL = "e"
RECORD_TYPE_MANUSCRIPT_CARTOGRAPHIC = "f"
RECORD_TYPE_PROJECTED_MEDIUM = "g"
RECORD_TYPE_NONPROJECTED_GRAPHIC = "k"
RECORD_TYPE_COMPUTER_FILE = "m"
RECORD_TYPE_SOUND_RECORDING_NONMUSICAL = "i"
RECORD_TYPE_SOUND_RECORDING_MUSICAL = "j"
RECORD_TYPE_KIT = "o"
RECORD_TYPE_MIXED_MATERIALS = "p"
RECORD_TYPE_TWO_DIMENSIONAL_GRAPHIC = "r"

BIB_LEVEL_MONOGRAPHIC_COMPONENT = "a"
BIB_LEVEL_SERIAL_COMPONENT = "b"
BIB_LEVEL_COLLECTION = "c"
BIB_LEVEL_SUBUNIT = "d"
BIB_LEVEL_INTEGRATING_RESOURCE = "i"
BIB_LEVEL_MONOGRAPH = "m"
BIB_LEVEL_SERIAL = "s"

CONTROL_TYPE_NO_SPECIFIED = " "
CONTROL_TYPE_ARCHIVAL = "a"

ENCODING_MARC8 = " "
ENCODING_UTF8 = "a"

CATALOGING_FORM_NON_ISBD = " "
CATALOGING_FORM_ISBD = "a"
CATALOGING_FORM_ISBD_NO_PUNCT = "c"
CATALOGING_FORM_ISBD_PUNCT_UNSPECIFIED = "i"
CATALOGING_FORM_NON_ISBD_NO_PUNCT = "n"
CATALOGING_FORM_UNKNOWN = "u"

MULTIPART_NOT_SPECIFIED = " "
MULTIPART_SET = "a"
MULTIPART_INDEPENDENT = "b"
MULTIPART_DEPENDENT = "c"

# Control field tags
TAG_CONTROL_NUMBER = "001"
TAG_CONTROL_NUMBER_IDENTIFIER = "003"
TAG_DATE_TIME_LATEST_TRANSACTION = "005"
TAG_ADDITIONAL_MATERIAL_CHARACTERISTICS = "006"
TAG_PHYSICAL_DESCRIPTION_FIXED_FIELD = "007"
TAG_FIXED_LENGTH_DATA_ELEMENTS = "008"

# Number and Code Fields
TAG_ISBN = "020"
TAG_ISSN = "022"
TAG_OTHER_STANDARD_IDENTIFIER = "024"
TAG_GOVERNMENT_DOCUMENT_NUMBER = "074"
TAG_LCCN = "010"
TAG_CODEN = "030"
TAG_SYSTEM_CONTROL_NUMBER = "035"
TAG_CATALOGING_SOURCE = "040"
TAG_LANGUAGE_CODE = "041"
TAG_AUTH_AREA_CODE = "043"
TAG_DDC = "082"
TAG_LCC = "050"
TAG_NLM = "060"
TAG_UDC = "080"

# Main Entry Fields
TAG_MAIN_ENTRY_PERSONAL_NAME = "100"
TAG_MAIN_ENTRY_CORPORATE_NAME = "110"
TAG_MAIN_ENTRY_MEETING_NAME = "111"
TAG_MAIN_ENTRY_UNIFORM_TITLE = "130"

# Title and Title-Related Fields
TAG_ABBREVIATED_TITLE = "210"
TAG_KEY_TITLE = "222"
TAG_UNIFORM_TITLE = "240"
TAG_TRANSLATION_OF_TITLE = "242"
TAG_TITLE_STATEMENT = "245"
TAG_VARYING_FORM_OF_TITLE = "246"
TAG_FORMER_TITLE = "247"

# Edition, Imprint, etc. Fields
TAG_EDITION_STATEMENT = "250"
TAG_PUBLICATION_DISTRIBUTION = "260"
TAG_PRODUCTION_PUBLICATION_DISTRIBUTION_MANUFACTURE = "264"
TAG_PROJECTED_PUBLICATION_DATE = "263"
TAG_CARTOGRAPHIC_MATHEMATICAL_DATA = "255"

# Physical Description Fields
TAG_PHYSICAL_DESCRIPTION = "300"
TAG_PLAYING_TIME = "306"
TAG_CURRENT_PUBLICATION_FREQUENCY = "310"
TAG_FORMER_PUBLICATION_FREQUENCY = "321"
TAG_CONTENT_TYPE = "336"
TAG_MEDIA_TYPE = "337"
TAG_CARRIER_TYPE = "338"

# Series Statement Fields
TAG_SERIES_STATEMENT_TITLE = "440"
TAG_SERIES_STATEMENT_UNTRACED = "490"

# Note Fields
TAG_GENERAL_NOTE = "500"
TAG_DISSERTATION_NOTE = "502"
TAG_BIBLIOGRAPHY_NOTE = "504"
TAG_FORMATTED_CONTENTS_NOTE = "505"
TAG_SUMMARY_NOTE = "520"
TAG_TARGET_AUDIENCE_NOTE = "521"
TAG_FUNDING_INFORMATION_NOTE = "536"
TAG_TERMS_OF_USE_NOTE = "540"
TAG_LOCATION_OF_ORIGINALS_NOTE = "535"
TAG_SYSTEM_DETAILS_NOTE = "538"
TAG_LANGUAGE_NOTE = "546"

# Subject Access Fields
TAG_SUBJECT_ADDED_ENTRY_PERSONAL_NAME = "600"
TAG_SUBJECT_ADDED_ENTRY_CORPORATE_NAME = "610"
TAG_SUBJECT_ADDED_ENTRY_MEETING_NAME = "611"
TAG_SUBJECT_ADDED_ENTRY_UNIFORM_TITLE = "630"
TAG_SUBJECT_ADDED_ENTRY_CHRONOLOGICAL_TERM = "648"
TAG_SUBJECT_ADDED_ENTRY_TOPICAL_TERM = "650"
TAG_SUBJECT_ADDED_ENTRY_GEOGRAPHIC_NAME = "651"
TAG_SUBJECT_ADDED_ENTRY_GENRE_FORM = "655"

# Added Entry Fields
TAG_ADDED_ENTRY_PERSONAL_NAME = "700"
TAG_ADDED_ENTRY_CORPORATE_NAME = "710"
TAG_ADDED_ENTRY_MEETING_NAME = "711"
TAG_ADDED_ENTRY_UNIFORM_TITLE = "730"
TAG_ADDED_ENTRY_RELATED_ANALYTICAL_TITLE = "740"

# Linking Entry Fields
TAG_MAIN_SERIES_ENTRY = "760"
TAG_SUB_SERIES_ENTRY = "762"
TAG_TRANSLATION_ENTRY = "765"
TAG_HAS_TRANSLATION_ENTRY = "767"
TAG_CONTINUES_ENTRY = "780"
TAG_CONTINUED_BY_ENTRY = "785"

# Series Added Entry Fields
TAG_SERIES_ADDED_ENTRY_PERSONAL_NAME = "800"
TAG_SERIES_ADDED_ENTRY_CORPORATE_NAME = "810"
TAG_SERIES_ADDED_ENTRY_MEETING_NAME = "811"
TAG_SERIES_ADDED_ENTRY_UNIFORM_TITLE = "830"

# Electronic Location and Access
TAG_ELECTRONIC_LOCATION_ACCESS = "856"

# Holdings and Local Data
TAG_HOLDINGS_LOCATION = "852"
TAG_LOCAL_ITEM_INFORMATION = "952"

# Delimiters
SUBFIELD_INDICATOR = "\x1f"
SUBFIELD_INDICATOR_CHAR = "$"
FIELD_TERMINATOR = "\x1e"
RECORD_TERMINATOR = "\x1d"

CONTROL_FIELD_TAGS: Set[str] = {
    "001", "002", "003", "004", "005", "006", "007", "008", "009"
}

STANDARD_LANGUAGE_CODES: Dict[str, str] = {
    "eng": "English", "fre": "French", "ger": "German", "spa": "Spanish",
    "ita": "Italian", "rus": "Russian", "chi": "Chinese", "jpn": "Japanese",
    "hin": "Hindi", "ara": "Arabic", "por": "Portuguese", "san": "Sanskrit",
    "tel": "Telugu", "tam": "Tamil", "kan": "Kannada", "mal": "Malayalam",
    "ben": "Bengali", "urd": "Urdu", "mar": "Marathi", "guj": "Gujarati",
    "lat": "Latin", "grc": "Classical Greek", "heb": "Hebrew", "kor": "Korean"
}

MARC_COUNTRY_CODES: Dict[str, str] = {
    "ii": "India", "xxu": "United States", "enk": "England", "fr": "France",
    "gw": "Germany", "ja": "Japan", "cc": "China", "ru": "Russia", "it": "Italy",
    "sp": "Spain", "at": "Australia", "cn": "Canada", "ne": "Netherlands"
}

def is_control_field(tag: str) -> bool:
    """Check if tag represents a control field (001-009)."""
    return tag in CONTROL_FIELD_TAGS or (len(tag) == 3 and tag.startswith("00"))

def validate_tag(tag: str) -> bool:
    """Validate 3-character numeric or alphanumeric MARC tag."""
    if not isinstance(tag, str) or len(tag) != 3:
        return False
    return tag.isalnum()
