"""ISO 639-2 and MARC 21 Standard Language Code Registry.

Defines standard 3-letter bibliographic and terminology codes for cataloging.
"""

from typing import Dict, Optional, List
from dataclasses import dataclass


@dataclass
class LanguageCode:
    code: str
    english_name: str
    french_name: str
    native_name: str
    script: str = "Latin"


MARC_LANGUAGES: Dict[str, LanguageCode] = {}

def _l(code: str, eng: str, fre: str, nat: str, script: str = "Latin"):
    MARC_LANGUAGES[code] = LanguageCode(code, eng, fre, nat, script)

_l("aar", "Afar", "afar", "Afaraf", "Latin")
_l("abk", "Abkhazian", "abkhaze", "аҧсуа бызшәа", "Cyrillic")
_l("ace", "Achinese", "aceh", "Acèh", "Latin")
_l("ach", "Acoli", "acoli", "Acoli", "Latin")
_l("ada", "Adangme", "adangme", "Dangme", "Latin")
_l("ady", "Adyghe", "adyghé", "адыгэбзэ", "Cyrillic")
_l("afa", "Afro-Asiatic languages", "afro-asiatiques", "Afroasiatic", "Latin")
_l("afh", "Afrihili", "afrihili", "Afrihili", "Latin")
_l("afr", "Afrikaans", "afrikaans", "Afrikaans", "Latin")
_l("ain", "Ainu", "aïnou", "アイヌ・イタㇰ", "Katakana")
_l("aka", "Akan", "akan", "Akan", "Latin")
_l("akk", "Akkadian", "akkadien", "𒀝𒅗𒁺𒌑", "Cuneiform")
_l("alb", "Albanian", "albanais", "Shqip", "Latin")
_l("ale", "Aleut", "aléoute", "Unangam Tunuu", "Latin")
_l("alg", "Algonquian languages", "algonquines", "Algonquian", "Latin")
_l("alt", "Southern Altai", "altai du sud", "алтай тили", "Cyrillic")
_l("amh", "Amharic", "amharique", "አማርኛ", "Ethiopic")
_l("ang", "English, Old (ca. 450-1100)", "anglo-saxon", "Englisc", "Latin")
_l("anp", "Angika", "angika", "अंगिका", "Devanagari")
_l("apa", "Apache languages", "apaches", "Apache", "Latin")
_l("ara", "Arabic", "arabe", "العربية", "Arabic")
_l("arc", "Official Aramaic", "araméen d'empire", "ܐܪܡܝܐ", "Syriac")
_l("arg", "Aragonese", "aragonais", "Aragonés", "Latin")
_l("arm", "Armenian", "arménien", "Հայերեն", "Armenian")
_l("arn", "Mapudungun", "mapudungun", "Mapudungun", "Latin")
_l("arp", "Arapaho", "arapaho", "Hinónoʼeitíít", "Latin")
_l("art", "Artificial languages", "artificielles", "Artificial", "Latin")
_l("arw", "Arawak", "arawak", "Lokono", "Latin")
_l("asm", "Assamese", "assamais", "অসমীয়া", "Bengali")
_l("ast", "Asturian", "asturien", "Asturianu", "Latin")
_l("ath", "Athapascan languages", "athapascanes", "Athapascan", "Latin")
_l("aus", "Australian languages", "australiennes", "Australian", "Latin")
_l("ava", "Avaric", "avar", "авар мацӀ", "Cyrillic")
_l("ave", "Avestan", "avestique", "avesta", "Avestan")
_l("awa", "Awadhi", "awadhi", "अवधी", "Devanagari")
_l("aym", "Aymara", "aymara", "Aymar aru", "Latin")
_l("aze", "Azerbaijani", "azéri", "Azərbaycan dili", "Latin")
_l("bad", "Banda languages", "banda", "Banda", "Latin")
_l("bai", "Bamileke languages", "bamiléké", "Bamileke", "Latin")
_l("bak", "Bashkir", "bachkir", "башҡорт теле", "Cyrillic")
_l("bal", "Baluchi", "baloutche", "بلوچی", "Arabic")
_l("bam", "Bambara", "bambara", "Bamanankan", "Latin")
_l("ban", "Balinese", "balinais", "Basa Bali", "Latin")
_l("baq", "Basque", "basque", "Euskara", "Latin")
_l("bas", "Basa", "basa", "Mbene", "Latin")
_l("bat", "Baltic languages", "baltiques", "Baltic", "Latin")
_l("bej", "Beja", "bedja", "Bidhaawyeet", "Latin")
_l("bel", "Belarusian", "biélorusse", "Беларуская", "Cyrillic")
_l("bem", "Bemba", "bemba", "Ichibemba", "Latin")
_l("ben", "Bengali", "bengali", "বাংলা", "Bengali")
_l("ber", "Berber languages", "berbères", "Tamaziɣt", "Tifinagh")
_l("bho", "Bhojpuri", "bhojpuri", "भोजपुरी", "Devanagari")
_l("bih", "Bihari languages", "langues biharis", "Bihari", "Latin")
_l("bik", "Bikol", "bikol", "Bikol", "Latin")
_l("bin", "Bini", "bini", "Èdó", "Latin")
_l("bis", "Bislama", "bichlamar", "Bislama", "Latin")
_l("bla", "Siksika", "blackfoot", "Siksiká", "Latin")
_l("bnt", "Bantu languages", "bantoues", "Bantu", "Latin")
_l("tib", "Tibetan", "tibétain", "བོད་ཡིག", "Tibetan")
_l("bos", "Bosnian", "bosniaque", "Bosanski", "Latin")
_l("bra", "Braj", "braj", "ब्रजभाषा", "Devanagari")
_l("bre", "Breton", "breton", "Brezhoneg", "Latin")
_l("btk", "Batak languages", "batak", "Batak", "Latin")
_l("bua", "Buriat", "bouriate", "буряад хэлэн", "Cyrillic")
_l("bug", "Buginese", "bugi", "Basa Ugi", "Latin")
_l("bul", "Bulgarian", "bulgare", "български език", "Cyrillic")
_l("bur", "Burmese", "birman", "မြန်မာစာ", "Myanmar")
_l("byn", "Blin", "blin", "ብሊን", "Ethiopic")
_l("cad", "Caddo", "caddo", "Hasí:nay", "Latin")
_l("cai", "Central American Indian languages", "indiennes d'Amérique centrale", "Central American", "Latin")
_l("car", "Galibi Carib", "caribe", "Kari'nja", "Latin")
_l("cat", "Catalan", "catalan", "Català", "Latin")
_l("cau", "Caucasian languages", "caucasiennes", "Caucasian", "Latin")
_l("ceb", "Cebuano", "cebuano", "Sinugboanon", "Latin")
_l("cel", "Celtic languages", "celtiques", "Celtic", "Latin")
_l("cha", "Chamorro", "chamorro", "Chamoru", "Latin")
_l("chb", "Chibcha", "chibcha", "Chibcha", "Latin")
_l("che", "Chechen", "tchétchène", "нохчийн мотт", "Cyrillic")
_l("chg", "Chagatai", "djaghataï", "چغتای", "Arabic")
_l("chi", "Chinese", "chinois", "中文", "Han")
_l("chk", "Chuukese", "chuuk", "Trukese", "Latin")
_l("chm", "Mari", "mari", "марий йылме", "Cyrillic")
_l("chn", "Chinook jargon", "chinook", "Chinuk wawa", "Latin")
_l("cho", "Choctaw", "choctaw", "Chahta", "Latin")
_l("chp", "Chipewyan", "chipewyan", "Dënesųłı̨né", "Latin")
_l("chr", "Cherokee", "cherokee", "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ", "Cherokee")
_l("chu", "Church Slavic", "slavon d'église", "ѩзыкъ словѣньскъ", "Cyrillic")
_l("chv", "Chuvash", "tchouvache", "чӑваш чӗлхи", "Cyrillic")
_l("chy", "Cheyenne", "cheyenne", "Tsėhésenėstsestȯtse", "Latin")
_l("cmc", "Chamic languages", "chames", "Chamic", "Latin")
_l("cop", "Coptic", "copte", "ϯⲙⲉⲧⲣⲉⲙⲛ̀ⲭⲏⲙⲓ", "Coptic")
_l("cor", "Cornish", "cornique", "Kernewek", "Latin")
_l("cos", "Corsican", "corse", "Corsu", "Latin")
_l("cpe", "Creoles, English-based", "créoles anglais", "Creole English", "Latin")
_l("cpf", "Creoles, French-based", "créoles français", "Creole French", "Latin")
_l("cpp", "Creoles, Portuguese-based", "créoles portugais", "Creole Portuguese", "Latin")
_l("cre", "Cree", "cree", "Nēhiyawēwin", "Canadian Aboriginal")
_l("crh", "Crimean Tatar", "tatar de Crimée", "Qırımtatar tili", "Latin")
_l("crp", "Creoles and pidgins", "créoles et pidgins", "Creoles", "Latin")
_l("csb", "Kashubian", "kachoube", "Kaszëbsczi jãzëk", "Latin")
_l("cus", "Cushitic languages", "couchitiques", "Cushitic", "Latin")
_l("cze", "Czech", "tchèque", "Čeština", "Latin")
_l("dak", "Dakota", "dakota", "Dakhótiyapi", "Latin")
_l("dan", "Danish", "danois", "Dansk", "Latin")
_l("dar", "Dargwa", "dargwa", "дарган мез", "Cyrillic")
_l("day", "Land Dayak languages", "dayak", "Dayak", "Latin")
_l("del", "Delaware", "delaware", "Lënape", "Latin")
_l("den", "Slave (Athapascan)", "esclave", "Dene Kʼe", "Latin")
_l("dgr", "Dogrib", "dogrib", "Tłı̨chǫ Yatiì", "Latin")
_l("din", "Dinka", "dinka", "Thuɔŋjäŋ", "Latin")
_l("div", "Divehi", "maldivien", "ދިވެހި", "Thaana")
_l("doi", "Dogri", "dogri", "डोगरी", "Devanagari")
_l("dra", "Dravidian languages", "dravidiennes", "Dravidian", "Latin")
_l("dsb", "Lower Sorbian", "bas-sorabe", "Dolnoserbski", "Latin")
_l("dua", "Duala", "douala", "Duala", "Latin")
_l("dum", "Dutch, Middle (ca. 1050-1350)", "néerlandais moyen", "Middelnederlands", "Latin")
_l("dut", "Dutch", "néerlandais", "Nederlands", "Latin")
_l("dyu", "Dyula", "dioula", "Julakan", "Latin")
_l("dzo", "Dzongkha", "dzongkha", "རྫོང་ཁ", "Tibetan")
_l("efi", "Efik", "efik", "Efik", "Latin")
_l("egy", "Egyptian (Ancient)", "égyptien", "Egyptian", "Hieroglyphic")
_l("eka", "Ekajuk", "ekajuk", "Ekajuk", "Latin")
_l("elx", "Elamite", "élamite", "Elamite", "Cuneiform")
_l("eng", "English", "anglais", "English", "Latin")
_l("enm", "English, Middle (1100-1500)", "anglais moyen", "Middle English", "Latin")
_l("epo", "Esperanto", "espéranto", "Esperanto", "Latin")
_l("est", "Estonian", "estonien", "Eesti", "Latin")
_l("ewe", "Ewe", "éwé", "Eʋegbe", "Latin")
_l("ewo", "Ewondo", "éwondo", "Kolo", "Latin")
_l("fan", "Fang", "fang", "Fang", "Latin")
_l("fao", "Faroese", "féroïen", "Føroyskt", "Latin")
_l("fat", "Fanti", "fanti", "Mfantse", "Latin")
_l("fij", "Fijian", "fidjien", "Na Vosa Vakaviti", "Latin")
_l("fil", "Filipino", "filipino", "Wikang Filipino", "Latin")
_l("fin", "Finnish", "finnois", "Suomi", "Latin")
_l("fiu", "Finno-Ugrian languages", "finno-ougriennes", "Finno-Ugrian", "Latin")
_l("fon", "Fon", "fon", "Fɔngbe", "Latin")
_l("fre", "French", "français", "Français", "Latin")
_l("frm", "French, Middle (ca. 1400-1600)", "français moyen", "Moyen français", "Latin")
_l("fro", "French, Old (842-ca. 1400)", "ancien français", "Ancien français", "Latin")
_l("frr", "Northern Frisian", "frison septentrional", "Nordfriisk", "Latin")
_l("frs", "Eastern Frisian", "frison oriental", "Seeltersk", "Latin")
_l("fry", "Western Frisian", "frison occidental", "Frysk", "Latin")
_l("ful", "Fulah", "peul", "Fulfulde", "Latin")
_l("fur", "Friulian", "frioulan", "Furlan", "Latin")
_l("gaa", "Ga", "ga", "Gã", "Latin")
_l("gay", "Gayo", "gayo", "Basa Gayo", "Latin")
_l("gba", "Gbaya", "gbaya", "Gbaya", "Latin")
_l("gem", "Germanic languages", "germaniques", "Germanic", "Latin")
_l("geo", "Georgian", "géorgien", "ქართული", "Georgian")
_l("ger", "German", "allemand", "Deutsch", "Latin")
_l("gez", "Geez", "guèze", "ግዕዝ", "Ethiopic")
_l("gil", "Gilbertese", "kiribati", "Taetae ni Kiribati", "Latin")
_l("gla", "Gaelic", "gaélique", "Gàidhlig", "Latin")
_l("gle", "Irish", "irlandais", "Gaeilge", "Latin")
_l("glg", "Galician", "galicien", "Galego", "Latin")
_l("glv", "Manx", "manx", "Gaelg", "Latin")
_l("gmh", "German, Middle High (ca. 1050-1500)", "moyen haut-allemand", "Mittelhochdeutsch", "Latin")
_l("goh", "German, Old High (ca. 750-1050)", "vieux haut-allemand", "Althochdeutsch", "Latin")
_l("gon", "Gondi", "gond", "Gōndi", "Latin")
_l("gor", "Gorontalo", "gorontalo", "Hulontalo", "Latin")
_l("got", "Gothic", "gothique", "Gutisko", "Latin")
_l("grb", "Grebo", "grebo", "Grebo", "Latin")
_l("grc", "Greek, Ancient (to 1453)", "grec ancien", "Ἑλληνική", "Greek")
_l("gre", "Greek, Modern (1453-)", "grec moderne", "Ελληνικά", "Greek")
_l("grn", "Guarani", "guarani", "Avañe'ẽ", "Latin")
_l("gsw", "Swiss German", "suisse alémanique", "Schwyzerdütsch", "Latin")
_l("guj", "Gujarati", "goudjrati", "ગુજરાતી", "Gujarati")
_l("gwi", "Gwich'in", "gwich'in", "Gwichʼin", "Latin")
_l("hai", "Haida", "haida", "X̲aat Kíl", "Latin")
_l("hat", "Haitian", "haïtien", "Kreyòl ayisyen", "Latin")
_l("hau", "Hausa", "haoussa", "Harshen Hausa", "Latin")
_l("haw", "Hawaiian", "hawaïen", "ʻŌlelo Hawaiʻi", "Latin")
_l("heb", "Hebrew", "hébreu", "עברית", "Hebrew")
_l("her", "Herero", "herero", "Otjiherero", "Latin")
_l("hil", "Hiligaynon", "hiligaynon", "Ilonggo", "Latin")
_l("him", "Himachali languages", "himachali", "Himachali", "Latin")
_l("hin", "Hindi", "hindi", "हिन्दी", "Devanagari")
_l("hit", "Hittite", "hittite", "Hittite", "Cuneiform")
_l("hmn", "Hmong", "hmong", "Hmoob", "Latin")
_l("hmo", "Hiri Motu", "hiri motu", "Hiri Motu", "Latin")
_l("hrv", "Croatian", "croate", "Hrvatski", "Latin")
_l("hsb", "Upper Sorbian", "haut-sorabe", "Hornjoserbsce", "Latin")
_l("hun", "Hungarian", "hongrois", "Magyar", "Latin")
_l("hup", "Hupa", "hupa", "Na:tinixwe", "Latin")
_l("iba", "Iban", "iban", "Jaku Iban", "Latin")
_l("ibo", "Igbo", "igbo", "Asụsụ Igbo", "Latin")
_l("ice", "Icelandic", "islandais", "Íslenska", "Latin")
_l("ido", "Ido", "ido", "Ido", "Latin")
_l("iii", "Sichuan Yi", "yi de Sichuan", "ꆈꌠ꒿", "Yi")
_l("ijo", "Ijo languages", "ijo", "Ịjọ", "Latin")
_l("iku", "Inuktitut", "inuktitut", "ᐃᓄᒃᑎᑐᑦ", "Inuktitut")
_l("ile", "Interlingue", "interlingue", "Interlingue", "Latin")
_l("ilo", "Iloko", "ilocano", "Pagsasao nga Ilokano", "Latin")
_l("ina", "Interlingua", "interlingua", "Interlingua", "Latin")
_l("inc", "Indic languages", "indo-aryennes", "Indic", "Latin")
_l("ind", "Indonesian", "indonésien", "Bahasa Indonesia", "Latin")
_l("ine", "Indo-European languages", "indo-européennes", "Indo-European", "Latin")
_l("inh", "Ingush", "ingouche", "ГӀалгӀай мотт", "Cyrillic")
_l("ipk", "Inupiaq", "inupiaq", "Iñupiatun", "Latin")
_l("ira", "Iranian languages", "iraniennes", "Iranian", "Latin")
_l("iro", "Iroquoian languages", "iroquoises", "Iroquoian", "Latin")
_l("ita", "Italian", "italien", "Italiano", "Latin")
_l("jav", "Javanese", "javanais", "Basa Jawa", "Latin")
_l("jbo", "Lojban", "lojban", "la .lojban.", "Latin")
_l("jpn", "Japanese", "japonais", "日本語", "Japanese")
_l("jpr", "Judeo-Persian", "judéo-persan", "Dzhidi", "Latin")
_l("jrb", "Judeo-Arabic", "judéo-arabe", "عربية يهودية", "Latin")
_l("kaa", "Kara-Kalpak", "karakalpak", "Qaraqalpaq tili", "Latin")
_l("kab", "Kabyle", "kabyle", "Taqbaylit", "Latin")
_l("kac", "Kachin", "kachin", "Jingpho", "Latin")
_l("kal", "Kalaallisut", "groenlandais", "Kalaallisut", "Latin")
_l("kam", "Kamba", "kamba", "Kikamba", "Latin")
_l("kan", "Kannada", "kannada", "ಕನ್ನಡ", "Kannada")
_l("kar", "Karen languages", "karen", "Karen", "Latin")
_l("kas", "Kashmiri", "kashmiri", "कॉशुर", "Arabic")
_l("kat", "Georgian (Alt)", "géorgien", "ქართული", "Georgian")
_l("kau", "Kanuri", "kanouri", "Kanuri", "Latin")
_l("kaw", "Kawi", "kawi", "Bhāṣa Kawi", "Latin")
_l("kaz", "Kazakh", "kazakh", "Қазақ тілі", "Cyrillic")
_l("kbd", "Kabardian", "kabarde", "Адыгэбзэ", "Cyrillic")
_l("kha", "Khasi", "khasi", "Ka Ktien Khasi", "Latin")
_l("khi", "Khoisan languages", "khoïsan", "Khoisan", "Latin")
_l("khm", "Khmer", "khmer", "ភាសាខ្មែរ", "Khmer")
_l("kho", "Khotanese", "khotanais", "Saka", "Latin")
_l("kik", "Kikuyu", "kikuyu", "Gĩkũyũ", "Latin")
_l("kin", "Kinyarwanda", "rwanda", "Ikinyarwanda", "Latin")
_l("kir", "Kirghiz", "kirghiz", "Кыргызча", "Cyrillic")
_l("kmb", "Kimbundu", "kimbundu", "Kimbundu", "Latin")
_l("kok", "Konkani", "konkani", "कोंकणी", "Devanagari")
_l("kom", "Komi", "kom", "коми кыв", "Cyrillic")
_l("kon", "Kongo", "kongo", "Kikongo", "Latin")
_l("kor", "Korean", "coréen", "한국어", "Hangul")
_l("kos", "Kosraean", "kosrae", "Kosrae", "Latin")
_l("kpe", "Kpelle", "kpellé", "Kpelle", "Latin")
_l("krc", "Karachay-Balkar", "karatchaï balkar", "Къарачай-малкъар тил", "Cyrillic")
_l("krl", "Karelian", "carélien", "Karjala", "Latin")
_l("kro", "Kru languages", "krou", "Kru", "Latin")
_l("kru", "Kurukh", "kurukh", "कुड़ुख़", "Devanagari")
_l("kua", "Kuanyama", "kuanyama", "Oshikwanyama", "Latin")
_l("kum", "Kumyk", "koumyk", "Къумукъ тил", "Cyrillic")
_l("kur", "Kurdish", "kurde", "Kurdî", "Arabic")
_l("kut", "Kutenai", "kutenai", "Ktunaxa", "Latin")
_l("lad", "Ladino", "judéo-espagnol", "Djudeo-espanyol", "Latin")
_l("lah", "Lahnda", "lahnda", "لہندا", "Arabic")
_l("lam", "Lamba", "lamba", "Ichilamba", "Latin")
_l("lao", "Lao", "lao", "ພາສາລາວ", "Lao")
_l("lat", "Latin", "latin", "Latina", "Latin")
_l("lav", "Latvian", "letton", "Latviešu", "Latin")
_l("lez", "Lezghian", "lezghien", "Лезги чӀал", "Cyrillic")
_l("lim", "Limburgan", "limbourgeois", "Limburgs", "Latin")
_l("lin", "Lingala", "lingala", "Lingála", "Latin")
_l("lit", "Lithuanian", "lituanien", "Lietuvių", "Latin")
_l("lol", "Mongo", "mongo", "Lomongo", "Latin")
_l("loz", "Lozi", "lozi", "Silozi", "Latin")
_l("ltz", "Luxembourgish", "luxembourgeois", "Lëtzebuergesch", "Latin")
_l("lua", "Luba-Lulua", "luba-lulua", "Tshiluba", "Latin")
_l("lub", "Luba-Katanga", "luba-katanga", "Kiluba", "Latin")
_l("lug", "Ganda", "ganda", "Oluganda", "Latin")
_l("lui", "Luiseno", "luiseno", "Cham'teuna", "Latin")
_l("lun", "Lunda", "lunda", "Chilunda", "Latin")
_l("luo", "Luo (Kenya and Tanzania)", "luo", "Dholuo", "Latin")
_l("lus", "Lushai", "lushai", "Mizo ṭawng", "Latin")
_l("mac", "Macedonian", "macédonien", "Македонски", "Cyrillic")
_l("mad", "Madurese", "madourais", "Basa Madhura", "Latin")
_l("mag", "Magahi", "magahi", "मगही", "Devanagari")
_l("mah", "Marshallese", "marshall", "Kajin M̧ajeļ", "Latin")
_l("mai", "Maithili", "maithili", "मैथिली", "Devanagari")
_l("mak", "Makasar", "makassar", "Basa Mangkasara", "Latin")
_l("mal", "Malayalam", "malayalam", "മലയാളം", "Malayalam")
_l("man", "Mandingo", "mandingue", "Mandenkan", "Latin")
_l("mao", "Maori", "maori", "Te Reo Māori", "Latin")
_l("map", "Austronesian languages", "austronésiennes", "Austronesian", "Latin")
_l("mar", "Marathi", "marathe", "मराठी", "Devanagari")
_l("mas", "Masai", "massaï", "Maa", "Latin")
_l("may", "Malay", "malais", "Bahasa Melayu", "Latin")
_l("mdf", "Moksha", "mokcha", "мокшень кяль", "Cyrillic")
_l("mdr", "Mandar", "mandar", "Mandar", "Latin")
_l("men", "Mende", "mendé", "Mɛnde yia", "Latin")
_l("mga", "Irish, Middle (900-1200)", "irlandais moyen", "Middle Irish", "Latin")
_l("mic", "Mi'kmaq", "micmac", "Mi'kmawi'simk", "Latin")
_l("min", "Minangkabau", "minangkabau", "Baso Minangkabau", "Latin")
_l("mis", "Uncoded languages", "non codées", "Uncoded", "Latin")
_l("mkh", "Mon-Khmer languages", "môn-khmer", "Mon-Khmer", "Latin")
_l("mlg", "Malagasy", "malgache", "Malagasy", "Latin")
_l("mlt", "Maltese", "maltais", "Malti", "Latin")
_l("mnc", "Manchu", "mandchou", "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ", "Manchu")
_l("mni", "Manipuri", "manipuri", "ꯃꯩꯇꯩꯂꯣꯟ", "Meitei Mayek")
_l("mno", "Manobo languages", "manobo", "Manobo", "Latin")
_l("moh", "Mohawk", "mohawk", "Kanienʼkéha", "Latin")
_l("mon", "Mongolian", "mongol", "Монгол хэл", "Cyrillic")
_l("mos", "Mossi", "moré", "Mooré", "Latin")
_l("mul", "Multiple languages", "multilingue", "Multiple", "Latin")
_l("mun", "Munda languages", "mounda", "Munda", "Latin")
_l("mus", "Creek", "creek", "Mvskoke", "Latin")
_l("mwl", "Mirandese", "mirandais", "Mirandés", "Latin")
_l("mwr", "Marwari", "marwari", "मारवाड़ी", "Devanagari")
_l("myn", "Mayan languages", "mayas", "Mayan", "Latin")
_l("myv", "Erzya", "erza", "эрзянь кель", "Cyrillic")
_l("nah", "Nahuatl languages", "nahuatl", "Nāhuatl", "Latin")
_l("nai", "North American Indian languages", "indiennes d'Amérique du Nord", "North American", "Latin")
_l("nap", "Neapolitan", "napolitain", "Napulitano", "Latin")
_l("nau", "Nauru", "nauruan", "Dorerin Naoero", "Latin")
_l("nav", "Navajo", "navaho", "Diné bizaad", "Latin")
_l("nbl", "Ndebele, South", "ndébélé du Sud", "isiNdebele", "Latin")
_l("nde", "Ndebele, North", "ndébélé du Nord", "isiNdebele", "Latin")
_l("ndo", "Ndonga", "ndonga", "Owambo", "Latin")
_l("nds", "Low German", "bas allemand", "Plattdüütsch", "Latin")
_l("nep", "Nepali", "népalais", "नेपाली", "Devanagari")
_l("new", "Nepal Bhasa", "nepal bhasa", "नेपाल भाषा", "Devanagari")
_l("nia", "Nias", "nias", "Li Niha", "Latin")
_l("nic", "Niger-Kordofanian languages", "nigéro-kordofaniennes", "Niger-Kordofanian", "Latin")
_l("niu", "Niuean", "niué", "Ko e vagahau Niuē", "Latin")
_l("nno", "Norwegian Nynorsk", "norvégien nynorsk", "Norsk Nynorsk", "Latin")
_l("nob", "Norwegian Bokmål", "norvégien bokmål", "Norsk Bokmål", "Latin")
_l("nog", "Nogai", "nogaï", "Ногай тили", "Cyrillic")
_l("non", "Norse, Old", "vieux norrois", "Dansk tunga", "Latin")
_l("nor", "Norwegian", "norvégien", "Norsk", "Latin")
_l("nqo", "N'Ko", "n'ko", "ߒߞߏ", "N'Ko")
_l("nso", "Pedi", "pedi", "Sesotho sa Leboa", "Latin")
_l("nub", "Nubian languages", "nubiennes", "Nubian", "Latin")
_l("nwc", "Classical Newari", "newari classique", "Classical Newari", "Latin")
_l("nya", "Chichewa", "chichewa", "Chichewa", "Latin")
_l("nym", "Nyamwezi", "nyamwezi", "Kinyamwezi", "Latin")
_l("nyn", "Nyankole", "nyankolé", "Runyankore", "Latin")
_l("nyo", "Nyoro", "nyoro", "Runyoro", "Latin")
_l("nzi", "Nzima", "nzema", "Nzema", "Latin")
_l("oci", "Occitan", "occitan", "Occitan", "Latin")
_l("oji", "Ojibwa", "ojibwa", "Anishinaabemowin", "Latin")
_l("ori", "Oriya", "oriya", "ଓଡ଼ିଆ", "Odia")
_l("orm", "Oromo", "oromo", "Afaan Oromoo", "Latin")
_l("osa", "Osage", "osage", "Wazhazhe", "Latin")
_l("oss", "Ossetian", "ossète", "Ирон ӕвзаг", "Cyrillic")
_l("ota", "Turkish, Ottoman (1500-1928)", "turc ottoman", "لسان عثمانی", "Arabic")
_l("oto", "Otomian languages", "otomi", "Otomian", "Latin")
_l("paa", "Papuan languages", "papoues", "Papuan", "Latin")
_l("pag", "Pangasinan", "pangasinan", "Salitan Pangasinan", "Latin")
_l("pal", "Pahlavi", "pahlavi", "Pahlavi", "Latin")
_l("pam", "Pampanga", "pampangan", "Kapampangan", "Latin")
_l("pan", "Panjabi", "pendjabi", "ਪੰਜਾਬੀ", "Gurmukhi")
_l("pap", "Papiamento", "papiamento", "Papiamentu", "Latin")
_l("pau", "Palauan", "palau", "Tekoi er a Belau", "Latin")
_l("peo", "Persian, Old (ca. 600-400 B.C.)", "vieux perse", "Old Persian", "Cuneiform")
_l("per", "Persian", "persan", "فارسی", "Arabic")
_l("phi", "Philippine languages", "philippines", "Philippine", "Latin")
_l("phn", "Phoenician", "phénicien", "Phoenician", "Phoenician")
_l("pli", "Pali", "pali", "पालि", "Devanagari")
_l("pol", "Polish", "polonais", "Polski", "Latin")
_l("pon", "Pohnpeian", "pohnpei", "Mahsen en Pohnpei", "Latin")
_l("por", "Portuguese", "portugais", "Português", "Latin")
_l("pra", "Prakrit languages", "prākrit", "Prakrit", "Latin")
_l("pro", "Provençal, Old (to 1500)", "provençal ancien", "Old Occitan", "Latin")
_l("pus", "Pushto", "pachto", "پښتو", "Arabic")
_l("que", "Quechua", "quechua", "Runa Simi", "Latin")
_l("raj", "Rajasthani", "rajasthani", "राजस्थानी", "Devanagari")
_l("rap", "Rapanui", "rapanui", "Vananga Rapa Nui", "Latin")
_l("rar", "Rarotongan", "rarotonga", "Māori Kūki ʻĀirani", "Latin")
_l("roa", "Romance languages", "romanes", "Romance", "Latin")
_l("roh", "Romansh", "romanche", "Rumantsch", "Latin")
_l("rom", "Romany", "tsigane", "Romani", "Latin")
_l("rum", "Romanian", "roumain", "Română", "Latin")
_l("run", "Rundi", "rundi", "Ikirundi", "Latin")
_l("rup", "Aromanian", "aroumain", "Armãneashti", "Latin")
_l("rus", "Russian", "russe", "Русский", "Cyrillic")
_l("sad", "Sadri", "sadri", "Sadri", "Latin")
_l("sag", "Sango", "sango", "Sängö", "Latin")
_l("sah", "Yakut", "iakoute", "Саха тыла", "Cyrillic")
_l("sai", "South American Indian languages", "indiennes d'Amérique du Sud", "South American", "Latin")
_l("sal", "Salishan languages", "salishennes", "Salishan", "Latin")
_l("sam", "Samaritan Aramaic", "samaritain", "ארמית שומרונית", "Samaritan")
_l("san", "Sanskrit", "sanskrit", "संस्कृतम्", "Devanagari")
_l("sas", "Sasak", "sasak", "Sasak", "Latin")
_l("sat", "Santali", "santal", "ᱥᱟᱱᱛᱟᱲᱤ", "Ol Chiki")
_l("scn", "Sicilian", "sicilien", "Sicilianu", "Latin")
_l("sco", "Scots", "écossais", "Scots", "Latin")
_l("sel", "Selkup", "selkoupe", "чулькмыт", "Cyrillic")
_l("sem", "Semitic languages", "sémitiques", "Semitic", "Latin")
_l("sga", "Irish, Old (to 900)", "vieil irlandais", "Old Irish", "Latin")
_l("sgn", "Sign Languages", "langues des signes", "Sign", "Latin")
_l("shn", "Shan", "chan", "လိၵ်ႈတႆး", "Myanmar")
_l("sid", "Sidamo", "sidamo", "Sidaamu Afoo", "Latin")
_l("sin", "Sinhala", "singhalais", "සිංහල", "Sinhala")
_l("sio", "Siouan languages", "sioux", "Siouan", "Latin")
_l("sit", "Sino-Tibetan languages", "sino-tibétaines", "Sino-Tibetan", "Latin")
_l("sla", "Slavic languages", "slaves", "Slavic", "Latin")
_l("slo", "Slovak", "slovaque", "Slovenčina", "Latin")
_l("slv", "Slovenian", "slovène", "Slovenščina", "Latin")
_l("sma", "Southern Sami", "sami du Sud", "Åarjelsaemien gïele", "Latin")
_l("sme", "Northern Sami", "sami du Nord", "Davvisámegiella", "Latin")
_l("smi", "Sami languages", "sami", "Sami", "Latin")
_l("smj", "Lule Sami", "sami de Lule", "Julevsámegiella", "Latin")
_l("smn", "Inari Sami", "sami d'Inari", "Anarâškielâ", "Latin")
_l("smo", "Samoan", "samoan", "Gagana fa'a Sāmoa", "Latin")
_l("sms", "Skolt Sami", "sami skolt", "Sääʹmǩiõll", "Latin")
_l("sna", "Shona", "shona", "chiShona", "Latin")
_l("snd", "Sindhi", "sindhi", "سنڌي", "Arabic")
_l("snk", "Soninke", "soninké", "Sooninkanxanne", "Latin")
_l("sog", "Sogdian", "sogdien", "Sogdian", "Latin")
_l("som", "Somali", "somali", "Soomaaliga", "Latin")
_l("son", "Songhai languages", "songhai", "Songhai", "Latin")
_l("sot", "Sotho, Southern", "sotho du Sud", "Sesotho", "Latin")
_l("spa", "Spanish", "espagnol", "Español", "Latin")
_l("srd", "Sardinian", "sarde", "Sardu", "Latin")
_l("srn", "Sranan Tongo", "sranan tongo", "Sranantongo", "Latin")
_l("srp", "Serbian", "serbe", "Српски", "Cyrillic")
_l("srr", "Serer", "sérère", "Seereer", "Latin")
_l("ssa", "Nilo-Saharan languages", "nilo-sahariennes", "Nilo-Saharan", "Latin")
_l("ssw", "Swati", "swati", "SiSwati", "Latin")
_l("suk", "Sukuma", "sukuma", "Kisukuma", "Latin")
_l("sun", "Sundanese", "soundanais", "Basa Sunda", "Latin")
_l("sus", "Susu", "soussou", "Sosoxui", "Latin")
_l("sux", "Sumerian", "sumérien", "𒅴𒂠", "Cuneiform")
_l("swa", "Swahili", "swahili", "Kiswahili", "Latin")
_l("swe", "Swedish", "suédois", "Svenska", "Latin")
_l("syc", "Classical Syriac", "syriaque classique", "ܣܘܪܝܝܐ", "Syriac")
_l("syr", "Syriac", "syriaque", "ܠܫܢܐ ܣܘܪܝܝܐ", "Syriac")
_l("tah", "Tahitian", "tahitien", "Reo Tahiti", "Latin")
_l("tai", "Tai languages", "tai", "Tai", "Latin")
_l("tam", "Tamil", "tamoul", "தமிழ்", "Tamil")
_l("tat", "Tatar", "tatar", "Татар теле", "Cyrillic")
_l("tel", "Telugu", "télougou", "తెలుగు", "Telugu")
_l("tem", "Timne", "temne", "KàThèmnè", "Latin")
_l("ter", "Tereno", "tereno", "Terêna", "Latin")
_l("tet", "Tetum", "tetum", "Lia-Tetun", "Latin")
_l("tgk", "Tajik", "tadjik", "Тоҷикӣ", "Cyrillic")
_l("tgl", "Tagalog", "tagalog", "Wikang Tagalog", "Latin")
_l("tha", "Thai", "thaï", "ภาษาไทย", "Thai")
_l("tig", "Tigre", "tigré", "ትግሬ", "Ethiopic")
_l("tir", "Tigrinya", "tigrigna", "ትግርኛ", "Ethiopic")
_l("tiv", "Tiv", "tiv", "Tiv", "Latin")
_l("tkl", "Tokelau", "tokelau", "Tokelau", "Latin")
_l("tlh", "Klingon", "klingon", "tlhIngan Hol", "Latin")
_l("tli", "Tlingit", "tlingit", "Lingít", "Latin")
_l("tmh", "Tamashek", "tamacheq", "Tamasheq", "Latin")
_l("tog", "Tonga (Nyasa)", "tonga", "chiTonga", "Latin")
_l("ton", "Tonga (Tonga Islands)", "tongan", "Lea Fakatonga", "Latin")
_l("tpi", "Tok Pisin", "tok pisin", "Tok Pisin", "Latin")
_l("tsi", "Tsimshian", "tsimshian", "Sm'algyax", "Latin")
_l("tsn", "Tswana", "tswana", "Setswana", "Latin")
_l("tso", "Tsonga", "tsonga", "Xitsonga", "Latin")
_l("tuk", "Turkmen", "turkmène", "Türkmençe", "Latin")
_l("tum", "Tumbuka", "tumbuka", "chiTumbuka", "Latin")
_l("tup", "Tupi languages", "tupi", "Tupi", "Latin")
_l("tur", "Turkish", "turc", "Türkçe", "Latin")
_l("tut", "Altaic languages", "altaïques", "Altaic", "Latin")
_l("tvl", "Tuvalu", "tuvalu", "Te Ggana Tuvalu", "Latin")
_l("twi", "Twi", "twi", "Twi", "Latin")
_l("tyv", "Tuvinian", "touva", "Тыва дыл", "Cyrillic")
_l("udm", "Udmurt", "oudmourte", "Удмурт кыл", "Cyrillic")
_l("uga", "Ugaritic", "ougaritique", "Ugaritic", "Cuneiform")
_l("uig", "Uighur", "ouïgour", "ئۇيغۇرچە", "Arabic")
_l("ukr", "Ukrainian", "ukrainien", "Українська", "Cyrillic")
_l("umb", "Umbundu", "umbundu", "Úmbúndú", "Latin")
_l("und", "Undetermined", "indéterminée", "Undetermined", "Latin")
_l("urd", "Urdu", "ourdou", "اردو", "Arabic")
_l("uzb", "Uzbek", "ouzbek", "Oʻzbekcha", "Latin")
_l("vai", "Vai", "vaï", "ꕙꔤ", "Vai")
_l("ven", "Venda", "venda", "Tshivenḓa", "Latin")
_l("vie", "Vietnamese", "vietnamien", "Tiếng Việt", "Latin")
_l("vol", "Volapük", "volapük", "Volapük", "Latin")
_l("vot", "Votic", "vote", "Vaďďa tšeeli", "Latin")
_l("wak", "Wakashan languages", "wakashanes", "Wakashan", "Latin")
_l("wal", "Walamo", "walamo", "Wolaytta", "Latin")
_l("war", "Waray", "waray", "Winaray", "Latin")
_l("was", "Washo", "washo", "Wá:šiw ʔítlu", "Latin")
_l("wel", "Welsh", "gallois", "Cymraeg", "Latin")
_l("wen", "Sorbian languages", "sorabes", "Sorbian", "Latin")
_l("wln", "Walloon", "wallon", "Walon", "Latin")
_l("wol", "Wolof", "wolof", "Wolof", "Latin")
_l("xal", "Kalmyk", "kalmouk", "Хальмг келн", "Cyrillic")
_l("xho", "Xhosa", "xhosa", "isiXhosa", "Latin")
_l("yao", "Yao", "yao", "Chiyao", "Latin")
_l("yap", "Yapese", "yapois", "Wa'ab", "Latin")
_l("yid", "Yiddish", "yiddish", "ייִדיש", "Hebrew")
_l("yor", "Yoruba", "yoruba", "Èdè Yorùbá", "Latin")
_l("ypk", "Yupik languages", "yupik", "Yupik", "Latin")
_l("zap", "Zapotec", "zapotèque", "Diidxazá", "Latin")
_l("zbl", "Blissymbols", "bliss", "Blissymbols", "Latin")
_l("zen", "Zenaga", "zenaga", "Tuḍḍungiyya", "Latin")
_l("zgh", "Standard Moroccan Tamazight", "amazighe standard marocain", "ⵜⴰⵎⴰⵣⵉⵖⵜ", "Tifinagh")
_l("zha", "Zhuang", "zhuang", "Vahcuengh", "Latin")
_l("znd", "Zande languages", "zandé", "Zande", "Latin")
_l("zul", "Zulu", "zoulou", "isiZulu", "Latin")
_l("zun", "Zuni", "zuni", "Shiwi'ma", "Latin")
_l("zxx", "No linguistic content", "pas de contenu linguistique", "None", "Latin")
_l("zza", "Zaza", "zaza", "Zazaki", "Latin")

def lookup_language(code: str) -> Optional[LanguageCode]:
    """Lookup language metadata by ISO 639-2 / MARC 3-letter code."""
    return MARC_LANGUAGES.get(code.strip().lower())

def search_languages(query: str) -> List[LanguageCode]:
    """Search languages by name or code prefix."""
    q = query.strip().lower()
    return [
        lang for lang in MARC_LANGUAGES.values()
        if q in lang.code.lower() or q in lang.english_name.lower() or q in lang.native_name.lower()
    ]
