"""Library of Congress MARC Code List for Countries Reference Registry.

Defines 2-3 character MARC country codes (008/15-17 and 044 field) and geopolitical data.
"""

from typing import Dict, List, Optional
from dataclasses import dataclass


@dataclass
class MarcCountryDefinition:
    marc_code: str
    country_name: str
    iso_alpha2: str
    iso_alpha3: str
    region: str
    currency_code: str
    is_historical: bool = False


MARC_COUNTRIES: Dict[str, MarcCountryDefinition] = {}

def _ctry(code: str, name: str, a2: str, a3: str, reg: str, curr: str, hist: bool = False):
    MARC_COUNTRIES[code] = MarcCountryDefinition(code, name, a2, a3, reg, curr, hist)

_ctry("af", "Afghanistan", "AF", "AFG", "Asia", "AFN")
_ctry("al", "Albania", "AL", "ALB", "Europe", "ALL")
_ctry("ag", "Algeria", "DZ", "DZA", "Africa", "DZD")
_ctry("an", "Andorra", "AD", "AND", "Europe", "EUR")
_ctry("ao", "Angola", "AO", "AGO", "Africa", "AOA")
_ctry("ay", "Antarctica", "AQ", "ATA", "Polar", "None")
_ctry("ac", "Antigua and Barbuda", "AG", "ATG", "Caribbean", "XCD")
_ctry("ar", "Argentina", "AR", "ARG", "South America", "ARS")
_ctry("am", "Armenia", "AM", "ARM", "Asia", "AMD")
_ctry("at", "Australia", "AU", "AUS", "Oceania", "AUD")
_ctry("au", "Austria", "AT", "AUT", "Europe", "EUR")
_ctry("aj", "Azerbaijan", "AZ", "AZE", "Asia", "AZN")
_ctry("bf", "Bahamas", "BS", "BHS", "Caribbean", "BSD")
_ctry("ba", "Bahrain", "BH", "BHR", "Asia", "BHD")
_ctry("bg", "Bangladesh", "BD", "BGD", "Asia", "BDT")
_ctry("bb", "Barbados", "BB", "BRB", "Caribbean", "BBD")
_ctry("bw", "Belarus", "BY", "BLR", "Europe", "BYN")
_ctry("be", "Belgium", "BE", "BEL", "Europe", "EUR")
_ctry("bh", "Belize", "BZ", "BLZ", "Central America", "BZD")
_ctry("dm", "Benin", "BJ", "BEN", "Africa", "XOF")
_ctry("bt", "Bhutan", "BT", "BTN", "Asia", "BTN")
_ctry("bo", "Bolivia", "BO", "BOL", "South America", "BOB")
_ctry("bn", "Bosnia and Herzegovina", "BA", "BIH", "Europe", "BAM")
_ctry("bs", "Botswana", "BW", "BWA", "Africa", "BWP")
_ctry("bl", "Brazil", "BR", "BRA", "South America", "BRL")
_ctry("bx", "Brunei", "BN", "BRN", "Asia", "BND")
_ctry("bu", "Bulgaria", "BG", "BGR", "Europe", "BGN")
_ctry("uv", "Burkina Faso", "BF", "BFA", "Africa", "XOF")
_ctry("bi", "Burundi", "BI", "BDI", "Africa", "BIF")
_ctry("cb", "Cambodia", "KH", "KHM", "Asia", "KHR")
_ctry("cm", "Cameroon", "CM", "CMR", "Africa", "XAF")
_ctry("cn", "Canada", "CA", "CAN", "North America", "CAD")
_ctry("cv", "Cabo Verde", "CV", "CPV", "Africa", "CVE")
_ctry("cf", "Central African Republic", "CF", "CAF", "Africa", "XAF")
_ctry("cd", "Chad", "TD", "TCD", "Africa", "XAF")
_ctry("cl", "Chile", "CL", "CHL", "South America", "CLP")
_ctry("cc", "China", "CN", "CHN", "Asia", "CNY")
_ctry("ck", "Colombia", "CO", "COL", "South America", "COP")
_ctry("cq", "Comoros", "KM", "COM", "Africa", "KMF")
_ctry("cg", "Congo (Brazzaville)", "CG", "COG", "Africa", "XAF")
_ctry("cx", "Congo (Kinshasa)", "CD", "COD", "Africa", "CDF")
_ctry("cr", "Costa Rica", "CR", "CRI", "Central America", "CRC")
_ctry("iv", "Cote d'Ivoire", "CI", "CIV", "Africa", "XOF")
_ctry("ci", "Croatia", "HR", "HRV", "Europe", "EUR")
_ctry("cu", "Cuba", "CU", "CUB", "Caribbean", "CUP")
_ctry("cy", "Cyprus", "CY", "CYP", "Europe", "EUR")
_ctry("xr", "Czech Republic", "CZ", "CZE", "Europe", "CZK")
_ctry("dk", "Denmark", "DK", "DNK", "Europe", "DKK")
_ctry("dj", "Djibouti", "DJ", "DJI", "Africa", "DJF")
_ctry("do", "Dominica", "DM", "DMA", "Caribbean", "XCD")
_ctry("dr", "Dominican Republic", "DO", "DOM", "Caribbean", "DOP")
_ctry("ec", "Ecuador", "EC", "ECU", "South America", "USD")
_ctry("ua", "Egypt", "EG", "EGY", "Africa", "EGP")
_ctry("es", "El Salvador", "SV", "SLV", "Central America", "USD")
_ctry("ek", "Equatorial Guinea", "GQ", "GNQ", "Africa", "XAF")
_ctry("ea", "Eritrea", "ER", "ERI", "Africa", "ERN")
_ctry("er", "Estonia", "EE", "EST", "Europe", "EUR")
_ctry("sz", "Eswatini", "SZ", "SWZ", "Africa", "SZL")
_ctry("et", "Ethiopia", "ET", "ETH", "Africa", "ETB")
_ctry("fj", "Fiji", "FJ", "FJI", "Oceania", "FJD")
_ctry("fi", "Finland", "FI", "FIN", "Europe", "EUR")
_ctry("fr", "France", "FR", "FRA", "Europe", "EUR")
_ctry("gb", "Gabon", "GA", "GAB", "Africa", "XAF")
_ctry("gm", "Gambia", "GM", "GMB", "Africa", "GMD")
_ctry("gs", "Georgia", "GE", "GEO", "Asia", "GEL")
_ctry("gw", "Germany", "DE", "DEU", "Europe", "EUR")
_ctry("gh", "Ghana", "GH", "GHA", "Africa", "GHS")
_ctry("gr", "Greece", "GR", "GRC", "Europe", "EUR")
_ctry("gl", "Greenland", "GL", "GRL", "Polar", "DKK")
_ctry("gd", "Grenada", "GD", "GRD", "Caribbean", "XCD")
_ctry("gt", "Guatemala", "GT", "GTM", "Central America", "GTQ")
_ctry("gv", "Guinea", "GN", "GIN", "Africa", "GNF")
_ctry("pg", "Guinea-Bissau", "GW", "GNB", "Africa", "XOF")
_ctry("gy", "Guyana", "GY", "GUY", "South America", "GYD")
_ctry("ht", "Haiti", "HT", "HTI", "Caribbean", "HTG")
_ctry("ho", "Honduras", "HN", "HND", "Central America", "HNL")
_ctry("hu", "Hungary", "HU", "HUN", "Europe", "HUF")
_ctry("ic", "Iceland", "IS", "ISL", "Europe", "ISK")
_ctry("ii", "India", "IN", "IND", "Asia", "INR")
_ctry("io", "Indonesia", "ID", "IDN", "Asia", "IDR")
_ctry("ir", "Iran", "IR", "IRN", "Asia", "IRR")
_ctry("iq", "Iraq", "IQ", "IRQ", "Asia", "IQD")
_ctry("ie", "Ireland", "IE", "IRL", "Europe", "EUR")
_ctry("is", "Israel", "IL", "ISR", "Asia", "ILS")
_ctry("it", "Italy", "IT", "ITA", "Europe", "EUR")
_ctry("jm", "Jamaica", "JM", "JAM", "Caribbean", "JMD")
_ctry("ja", "Japan", "JP", "JPN", "Asia", "JPY")
_ctry("jo", "Jordan", "JO", "JOR", "Asia", "JOD")
_ctry("kz", "Kazakhstan", "KZ", "KAZ", "Asia", "KZT")
_ctry("ke", "Kenya", "KE", "KEN", "Africa", "KES")
_ctry("kn", "Korea (North)", "KP", "PRK", "Asia", "KPW")
_ctry("ko", "Korea (South)", "KR", "KOR", "Asia", "KRW")
_ctry("ku", "Kuwait", "KW", "KWT", "Asia", "KWD")
_ctry("kg", "Kyrgyzstan", "KG", "KGZ", "Asia", "KGS")
_ctry("ls", "Laos", "LA", "LAO", "Asia", "LAK")
_ctry("lv", "Latvia", "LV", "LVA", "Europe", "EUR")
_ctry("le", "Lebanon", "LB", "LBN", "Asia", "LBP")
_ctry("lb", "Liberia", "LR", "LBR", "Africa", "LRD")
_ctry("ly", "Libya", "LY", "LBY", "Africa", "LYD")
_ctry("li", "Liechtenstein", "LI", "LIE", "Europe", "CHF")
_ctry("lh", "Lithuania", "LT", "LTU", "Europe", "EUR")
_ctry("lu", "Luxembourg", "LU", "LUX", "Europe", "EUR")
_ctry("mg", "Madagascar", "MG", "MDG", "Africa", "MGA")
_ctry("mw", "Malawi", "MW", "MWI", "Africa", "MWK")
_ctry("my", "Malaysia", "MY", "MYS", "Asia", "MYR")
_ctry("mv", "Maldives", "MV", "MDV", "Asia", "MVR")
_ctry("ml", "Mali", "ML", "MLI", "Africa", "XOF")
_ctry("mm", "Malta", "MT", "MLT", "Europe", "EUR")
_ctry("mr", "Mauritania", "MR", "MRT", "Africa", "MRU")
_ctry("mu", "Mauritius", "MU", "MUS", "Africa", "MUR")
_ctry("mx", "Mexico", "MX", "MEX", "North America", "MXN")
_ctry("mc", "Monaco", "MC", "MCO", "Europe", "EUR")
_ctry("mp", "Mongolia", "MN", "MNG", "Asia", "MNT")
_ctry("mo", "Montenegro", "ME", "MNE", "Europe", "EUR")
_ctry("mr", "Morocco", "MA", "MAR", "Africa", "MAD")
_ctry("mz", "Mozambique", "MZ", "MOZ", "Africa", "MZN")
_ctry("bm", "Myanmar", "MM", "MMR", "Asia", "MMK")
_ctry("na", "Namibia", "NA", "NAM", "Africa", "NAD")
_ctry("nr", "Nauru", "NR", "NRU", "Oceania", "AUD")
_ctry("np", "Nepal", "NP", "NPL", "Asia", "NPR")
_ctry("ne", "Netherlands", "NL", "NLD", "Europe", "EUR")
_ctry("nz", "New Zealand", "NZ", "NZL", "Oceania", "NZD")
_ctry("nq", "Nicaragua", "NI", "NIC", "Central America", "NIO")
_ctry("ng", "Niger", "NE", "NER", "Africa", "XOF")
_ctry("ni", "Nigeria", "NG", "NGA", "Africa", "NGN")
_ctry("no", "Norway", "NO", "NOR", "Europe", "NOK")
_ctry("om", "Oman", "OM", "OMN", "Asia", "OMR")
_ctry("pk", "Pakistan", "PK", "PAK", "Asia", "PKR")
_ctry("pw", "Palau", "PW", "PLW", "Oceania", "USD")
_ctry("pn", "Panama", "PA", "PAN", "Central America", "PAB")
_ctry("pp", "Papua New Guinea", "PG", "PNG", "Oceania", "PGK")
_ctry("py", "Paraguay", "PY", "PRY", "South America", "PYG")
_ctry("pe", "Peru", "PE", "PER", "South America", "PEN")
_ctry("ph", "Philippines", "PH", "PHL", "Asia", "PHP")
_ctry("pl", "Poland", "PL", "POL", "Europe", "PLN")
_ctry("pt", "Portugal", "PT", "PRT", "Europe", "EUR")
_ctry("qa", "Qatar", "QA", "QAT", "Asia", "QAR")
_ctry("ro", "Romania", "RO", "ROU", "Europe", "RON")
_ctry("ru", "Russia", "RU", "RUS", "Europe", "RUB")
_ctry("rw", "Rwanda", "RW", "RWA", "Africa", "RWF")
_ctry("kn", "Saint Kitts and Nevis", "KN", "KNA", "Caribbean", "XCD")
_ctry("lc", "Saint Lucia", "LC", "LCA", "Caribbean", "XCD")
_ctry("ws", "Samoa", "WS", "WSM", "Oceania", "WST")
_ctry("sm", "San Marino", "SM", "SMR", "Europe", "EUR")
_ctry("sa", "Saudi Arabia", "SA", "SAU", "Asia", "SAR")
_ctry("sg", "Senegal", "SN", "SEN", "Africa", "XOF")
_ctry("se", "Serbia", "RS", "SRB", "Europe", "RSD")
_ctry("sc", "Seychelles", "SC", "SYC", "Africa", "SCR")
_ctry("sl", "Sierra Leone", "SL", "SLE", "Africa", "SLL")
_ctry("si", "Singapore", "SG", "SGP", "Asia", "SGD")
_ctry("xo", "Slovakia", "SK", "SVK", "Europe", "EUR")
_ctry("xv", "Slovenia", "SI", "SVN", "Europe", "EUR")
_ctry("bp", "Solomon Islands", "SB", "SLB", "Oceania", "SBD")
_ctry("so", "Somalia", "SO", "SOM", "Africa", "SOS")
_ctry("za", "South Africa", "ZA", "ZAF", "Africa", "ZAR")
_ctry("sp", "Spain", "ES", "ESP", "Europe", "EUR")
_ctry("ce", "Sri Lanka", "LK", "LKA", "Asia", "LKR")
_ctry("su", "Sudan", "SD", "SDN", "Africa", "SDG")
_ctry("sr", "Suriname", "SR", "SUR", "South America", "SRD")
_ctry("sw", "Sweden", "SE", "SWE", "Europe", "SEK")
_ctry("sz", "Switzerland", "CH", "CHE", "Europe", "CHF")
_ctry("sy", "Syria", "SY", "SYR", "Asia", "SYP")
_ctry("ti", "Tajikistan", "TJ", "TJK", "Asia", "TJS")
_ctry("tz", "Tanzania", "TZ", "TZA", "Africa", "TZS")
_ctry("th", "Thailand", "TH", "THA", "Asia", "THB")
_ctry("to", "Togo", "TG", "TGO", "Africa", "XOF")
_ctry("tg", "Tonga", "TO", "TON", "Oceania", "TOP")
_ctry("tt", "Trinidad and Tobago", "TT", "TTO", "Caribbean", "TTD")
_ctry("ti", "Tunisia", "TN", "TUN", "Africa", "TND")
_ctry("ts", "Turkey", "TR", "TUR", "Asia", "TRY")
_ctry("tk", "Turkmenistan", "TM", "TKM", "Asia", "TMT")
_ctry("tv", "Tuvalu", "TV", "TUV", "Oceania", "AUD")
_ctry("ug", "Uganda", "UG", "UGA", "Africa", "UGX")
_ctry("un", "Ukraine", "UA", "UKR", "Europe", "UAH")
_ctry("ts", "United Arab Emirates", "AE", "ARE", "Asia", "AED")
_ctry("uk", "United Kingdom", "GB", "GBR", "Europe", "GBP")
_ctry("enk", "England", "GB", "GBR", "Europe", "GBP")
_ctry("stk", "Scotland", "GB", "GBR", "Europe", "GBP")
_ctry("wlk", "Wales", "GB", "GBR", "Europe", "GBP")
_ctry("nik", "Northern Ireland", "GB", "GBR", "Europe", "GBP")
_ctry("xxu", "United States", "US", "USA", "North America", "USD")
_ctry("uy", "Uruguay", "UY", "URY", "South America", "UYU")
_ctry("uz", "Uzbekistan", "UZ", "UZB", "Asia", "UZS")
_ctry("nn", "Vanuatu", "VU", "VUT", "Oceania", "VUV")
_ctry("vc", "Vatican City", "VA", "VAT", "Europe", "EUR")
_ctry("ve", "Venezuela", "VE", "VEN", "South America", "VES")
_ctry("vn", "Vietnam", "VN", "VNM", "Asia", "VND")
_ctry("ye", "Yemen", "YE", "YEM", "Asia", "YER")
_ctry("za", "Zambia", "ZM", "ZMB", "Africa", "ZMW")
_ctry("rh", "Zimbabwe", "ZW", "ZWE", "Africa", "ZWL")
_ctry("alu", "Alabama (State)", "US", "USA", "North America", "USD")
_ctry("aku", "Alaska (State)", "US", "USA", "North America", "USD")
_ctry("azu", "Arizona (State)", "US", "USA", "North America", "USD")
_ctry("aru", "Arkansas (State)", "US", "USA", "North America", "USD")
_ctry("cau", "California (State)", "US", "USA", "North America", "USD")
_ctry("cou", "Colorado (State)", "US", "USA", "North America", "USD")
_ctry("ctu", "Connecticut (State)", "US", "USA", "North America", "USD")
_ctry("deu", "Delaware (State)", "US", "USA", "North America", "USD")
_ctry("dcu", "District of Columbia (State)", "US", "USA", "North America", "USD")
_ctry("flu", "Florida (State)", "US", "USA", "North America", "USD")
_ctry("gau", "Georgia (State)", "US", "USA", "North America", "USD")
_ctry("hiu", "Hawaii (State)", "US", "USA", "North America", "USD")
_ctry("idu", "Idaho (State)", "US", "USA", "North America", "USD")
_ctry("ilu", "Illinois (State)", "US", "USA", "North America", "USD")
_ctry("inu", "Indiana (State)", "US", "USA", "North America", "USD")
_ctry("iau", "Iowa (State)", "US", "USA", "North America", "USD")
_ctry("ksu", "Kansas (State)", "US", "USA", "North America", "USD")
_ctry("kyu", "Kentucky (State)", "US", "USA", "North America", "USD")
_ctry("lau", "Louisiana (State)", "US", "USA", "North America", "USD")
_ctry("meu", "Maine (State)", "US", "USA", "North America", "USD")
_ctry("mdu", "Maryland (State)", "US", "USA", "North America", "USD")
_ctry("mau", "Massachusetts (State)", "US", "USA", "North America", "USD")
_ctry("miu", "Michigan (State)", "US", "USA", "North America", "USD")
_ctry("mnu", "Minnesota (State)", "US", "USA", "North America", "USD")
_ctry("msu", "Mississippi (State)", "US", "USA", "North America", "USD")
_ctry("mou", "Missouri (State)", "US", "USA", "North America", "USD")
_ctry("mtu", "Montana (State)", "US", "USA", "North America", "USD")
_ctry("neu", "Nebraska (State)", "US", "USA", "North America", "USD")
_ctry("nvu", "Nevada (State)", "US", "USA", "North America", "USD")
_ctry("nhu", "New Hampshire (State)", "US", "USA", "North America", "USD")
_ctry("nju", "New Jersey (State)", "US", "USA", "North America", "USD")
_ctry("nmu", "New Mexico (State)", "US", "USA", "North America", "USD")
_ctry("nyu", "New York (State)", "US", "USA", "North America", "USD")
_ctry("ncu", "North Carolina (State)", "US", "USA", "North America", "USD")
_ctry("ndu", "North Dakota (State)", "US", "USA", "North America", "USD")
_ctry("ohu", "Ohio (State)", "US", "USA", "North America", "USD")
_ctry("oku", "Oklahoma (State)", "US", "USA", "North America", "USD")
_ctry("oru", "Oregon (State)", "US", "USA", "North America", "USD")
_ctry("pau", "Pennsylvania (State)", "US", "USA", "North America", "USD")
_ctry("riu", "Rhode Island (State)", "US", "USA", "North America", "USD")
_ctry("scu", "South Carolina (State)", "US", "USA", "North America", "USD")
_ctry("sdu", "South Dakota (State)", "US", "USA", "North America", "USD")
_ctry("tnu", "Tennessee (State)", "US", "USA", "North America", "USD")
_ctry("txu", "Texas (State)", "US", "USA", "North America", "USD")
_ctry("utu", "Utah (State)", "US", "USA", "North America", "USD")
_ctry("vtu", "Vermont (State)", "US", "USA", "North America", "USD")
_ctry("vau", "Virginia (State)", "US", "USA", "North America", "USD")
_ctry("wau", "Washington (State)", "US", "USA", "North America", "USD")
_ctry("wvu", "West Virginia (State)", "US", "USA", "North America", "USD")
_ctry("wiu", "Wisconsin (State)", "US", "USA", "North America", "USD")
_ctry("wyu", "Wyoming (State)", "US", "USA", "North America", "USD")
_ctry("abc", "Alberta (Province)", "CA", "CAN", "North America", "CAD")
_ctry("bcc", "British Columbia (Province)", "CA", "CAN", "North America", "CAD")
_ctry("mbc", "Manitoba (Province)", "CA", "CAN", "North America", "CAD")
_ctry("nkc", "New Brunswick (Province)", "CA", "CAN", "North America", "CAD")
_ctry("nfc", "Newfoundland and Labrador (Province)", "CA", "CAN", "North America", "CAD")
_ctry("ntc", "Northwest Territories (Province)", "CA", "CAN", "North America", "CAD")
_ctry("nsc", "Nova Scotia (Province)", "CA", "CAN", "North America", "CAD")
_ctry("nuc", "Nunavut (Province)", "CA", "CAN", "North America", "CAD")
_ctry("onc", "Ontario (Province)", "CA", "CAN", "North America", "CAD")
_ctry("pic", "Prince Edward Island (Province)", "CA", "CAN", "North America", "CAD")
_ctry("quc", "Quebec (Province)", "CA", "CAN", "North America", "CAD")
_ctry("snc", "Saskatchewan (Province)", "CA", "CAN", "North America", "CAD")
_ctry("ykc", "Yukon (Province)", "CA", "CAN", "North America", "CAD")

def lookup_marc_country(code: str) -> Optional[MarcCountryDefinition]:
    return MARC_COUNTRIES.get(code.strip().lower())
