"""LCSH to DDC and LCC Classification Crosswalk Engine.

Maps Library of Congress Subject Headings directly to standard classification marks.
"""

from typing import Dict, List, Optional
from dataclasses import dataclass


@dataclass
class ClassificationMapping:
    subject_term: str
    primary_ddc: str
    primary_lcc: str
    secondary_ddc: Optional[str] = None
    secondary_lcc: Optional[str] = None
    discipline: str = ""


LCSH_TO_CLASSIFICATION_MAP: Dict[str, ClassificationMapping] = {}

def _map(term: str, ddc: str, lcc: str, ddc2: Optional[str], lcc2: Optional[str], disc: str):
    LCSH_TO_CLASSIFICATION_MAP[term.lower()] = ClassificationMapping(term, ddc, lcc, ddc2, lcc2, disc)

_map("Clean code", "005.1", "QA76.76.C65", "005.13", "QA76.73", "Software Engineering")
_map("Agile software development", "005.1", "QA76.758", "658.404", "HD69.P75", "Computer Science")
_map("Object-oriented programming", "005.117", "QA76.64", "005.133", "QA76.73", "Computer Science")
_map("Data structures (Computer science)", "005.73", "QA76.9.D35", "518.1", "QA76.9.A43", "Computer Science")
_map("Algorithms", "518.1", "QA76.9.A43", "005.1", "QA76.758", "Mathematics & Computing")
_map("Relational databases", "005.756", "QA76.9.D3", "005.74", "QA76.9.D32", "Databases")
_map("Operating systems (Computers)", "005.43", "QA76.76.O63", "004.2", "QA76.9.A73", "Systems")
_map("Computer architecture", "004.22", "QA76.9.A73", "621.39", "TK7888.3", "Computer Engineering")
_map("Computer networks", "004.6", "TK5105.5", "004.678", "TK5105.875", "Telecommunications")
_map("Artificial intelligence", "006.3", "Q335", "006.31", "Q325.5", "Computer Science")
_map("Machine learning", "006.31", "Q325.5", "519.5", "QA276", "Artificial Intelligence")
_map("Deep learning", "006.32", "Q325.7", "006.3", "Q335", "Artificial Intelligence")
_map("Natural language processing", "006.35", "QA76.9.N38", "410.285", "P98", "Linguistics & AI")
_map("Cryptography", "005.82", "QA76.9.A25", "652.8", "Z103", "Computer Security")
_map("Computer security", "005.8", "QA76.9.A25", "658.478", "HF5548.37", "Security")
_map("Software testing", "005.14", "QA76.76.T48", "005.1", "QA76.758", "Software Engineering")
_map("Web services", "006.76", "TK5105.888", "004.678", "TK5105.875", "Internet")
_map("Distributed computing", "004.36", "QA76.9.D5", "004.6", "TK5105.5", "Computer Systems")
_map("Cloud computing", "004.6782", "QA76.585", "005.74", "QA76.9.D3", "Computing")
_map("Microservices", "005.1", "QA76.758", "004.36", "QA76.9.D5", "Software Architecture")
_map("Algebra", "500", "Q10", None, None, "Academic Core Algebra")
_map("Algebra -- Research methodology", "500.072", "Q10.R4", None, None, "Methodology in Algebra")
_map("Algebra -- History and criticism", "500.09", "Q10.H5", None, None, "History of Algebra")
_map("Algebra -- Mathematical models", "500.0151", "Q10.M3", None, None, "Mathematical Modeling in Algebra")
_map("Calculus", "501", "Q11", None, None, "Academic Core Calculus")
_map("Calculus -- Research methodology", "501.072", "Q11.R4", None, None, "Methodology in Calculus")
_map("Calculus -- History and criticism", "501.09", "Q11.H5", None, None, "History of Calculus")
_map("Calculus -- Mathematical models", "501.0151", "Q11.M3", None, None, "Mathematical Modeling in Calculus")
_map("Geometry", "502", "Q12", None, None, "Academic Core Geometry")
_map("Geometry -- Research methodology", "502.072", "Q12.R4", None, None, "Methodology in Geometry")
_map("Geometry -- History and criticism", "502.09", "Q12.H5", None, None, "History of Geometry")
_map("Geometry -- Mathematical models", "502.0151", "Q12.M3", None, None, "Mathematical Modeling in Geometry")
_map("Topology", "503", "Q13", None, None, "Academic Core Topology")
_map("Topology -- Research methodology", "503.072", "Q13.R4", None, None, "Methodology in Topology")
_map("Topology -- History and criticism", "503.09", "Q13.H5", None, None, "History of Topology")
_map("Topology -- Mathematical models", "503.0151", "Q13.M3", None, None, "Mathematical Modeling in Topology")
_map("Number theory", "504", "Q14", None, None, "Academic Core Number theory")
_map("Number theory -- Research methodology", "504.072", "Q14.R4", None, None, "Methodology in Number theory")
_map("Number theory -- History and criticism", "504.09", "Q14.H5", None, None, "History of Number theory")
_map("Number theory -- Mathematical models", "504.0151", "Q14.M3", None, None, "Mathematical Modeling in Number theory")
_map("Probability", "505", "Q15", None, None, "Academic Core Probability")
_map("Probability -- Research methodology", "505.072", "Q15.R4", None, None, "Methodology in Probability")
_map("Probability -- History and criticism", "505.09", "Q15.H5", None, None, "History of Probability")
_map("Probability -- Mathematical models", "505.0151", "Q15.M3", None, None, "Mathematical Modeling in Probability")
_map("Statistics", "506", "Q16", None, None, "Academic Core Statistics")
_map("Statistics -- Research methodology", "506.072", "Q16.R4", None, None, "Methodology in Statistics")
_map("Statistics -- History and criticism", "506.09", "Q16.H5", None, None, "History of Statistics")
_map("Statistics -- Mathematical models", "506.0151", "Q16.M3", None, None, "Mathematical Modeling in Statistics")
_map("Mechanics", "507", "Q17", None, None, "Academic Core Mechanics")
_map("Mechanics -- Research methodology", "507.072", "Q17.R4", None, None, "Methodology in Mechanics")
_map("Mechanics -- History and criticism", "507.09", "Q17.H5", None, None, "History of Mechanics")
_map("Mechanics -- Mathematical models", "507.0151", "Q17.M3", None, None, "Mathematical Modeling in Mechanics")
_map("Thermodynamics", "508", "Q18", None, None, "Academic Core Thermodynamics")
_map("Thermodynamics -- Research methodology", "508.072", "Q18.R4", None, None, "Methodology in Thermodynamics")
_map("Thermodynamics -- History and criticism", "508.09", "Q18.H5", None, None, "History of Thermodynamics")
_map("Thermodynamics -- Mathematical models", "508.0151", "Q18.M3", None, None, "Mathematical Modeling in Thermodynamics")
_map("Electromagnetism", "509", "Q19", None, None, "Academic Core Electromagnetism")
_map("Electromagnetism -- Research methodology", "509.072", "Q19.R4", None, None, "Methodology in Electromagnetism")
_map("Electromagnetism -- History and criticism", "509.09", "Q19.H5", None, None, "History of Electromagnetism")
_map("Electromagnetism -- Mathematical models", "509.0151", "Q19.M3", None, None, "Mathematical Modeling in Electromagnetism")
_map("Optics", "510", "Q20", None, None, "Academic Core Optics")
_map("Optics -- Research methodology", "510.072", "Q20.R4", None, None, "Methodology in Optics")
_map("Optics -- History and criticism", "510.09", "Q20.H5", None, None, "History of Optics")
_map("Optics -- Mathematical models", "510.0151", "Q20.M3", None, None, "Mathematical Modeling in Optics")
_map("Acoustics", "511", "Q21", None, None, "Academic Core Acoustics")
_map("Acoustics -- Research methodology", "511.072", "Q21.R4", None, None, "Methodology in Acoustics")
_map("Acoustics -- History and criticism", "511.09", "Q21.H5", None, None, "History of Acoustics")
_map("Acoustics -- Mathematical models", "511.0151", "Q21.M3", None, None, "Mathematical Modeling in Acoustics")
_map("Quantum mechanics", "512", "Q22", None, None, "Academic Core Quantum mechanics")
_map("Quantum mechanics -- Research methodology", "512.072", "Q22.R4", None, None, "Methodology in Quantum mechanics")
_map("Quantum mechanics -- History and criticism", "512.09", "Q22.H5", None, None, "History of Quantum mechanics")
_map("Quantum mechanics -- Mathematical models", "512.0151", "Q22.M3", None, None, "Mathematical Modeling in Quantum mechanics")
_map("Organic chemistry", "513", "Q23", None, None, "Academic Core Organic chemistry")
_map("Organic chemistry -- Research methodology", "513.072", "Q23.R4", None, None, "Methodology in Organic chemistry")
_map("Organic chemistry -- History and criticism", "513.09", "Q23.H5", None, None, "History of Organic chemistry")
_map("Organic chemistry -- Mathematical models", "513.0151", "Q23.M3", None, None, "Mathematical Modeling in Organic chemistry")
_map("Inorganic chemistry", "514", "Q24", None, None, "Academic Core Inorganic chemistry")
_map("Inorganic chemistry -- Research methodology", "514.072", "Q24.R4", None, None, "Methodology in Inorganic chemistry")
_map("Inorganic chemistry -- History and criticism", "514.09", "Q24.H5", None, None, "History of Inorganic chemistry")
_map("Inorganic chemistry -- Mathematical models", "514.0151", "Q24.M3", None, None, "Mathematical Modeling in Inorganic chemistry")
_map("Biochemistry", "515", "Q25", None, None, "Academic Core Biochemistry")
_map("Biochemistry -- Research methodology", "515.072", "Q25.R4", None, None, "Methodology in Biochemistry")
_map("Biochemistry -- History and criticism", "515.09", "Q25.H5", None, None, "History of Biochemistry")
_map("Biochemistry -- Mathematical models", "515.0151", "Q25.M3", None, None, "Mathematical Modeling in Biochemistry")
_map("Molecular biology", "516", "Q26", None, None, "Academic Core Molecular biology")
_map("Molecular biology -- Research methodology", "516.072", "Q26.R4", None, None, "Methodology in Molecular biology")
_map("Molecular biology -- History and criticism", "516.09", "Q26.H5", None, None, "History of Molecular biology")
_map("Molecular biology -- Mathematical models", "516.0151", "Q26.M3", None, None, "Mathematical Modeling in Molecular biology")
_map("Genetics", "517", "Q27", None, None, "Academic Core Genetics")
_map("Genetics -- Research methodology", "517.072", "Q27.R4", None, None, "Methodology in Genetics")
_map("Genetics -- History and criticism", "517.09", "Q27.H5", None, None, "History of Genetics")
_map("Genetics -- Mathematical models", "517.0151", "Q27.M3", None, None, "Mathematical Modeling in Genetics")
_map("Microbiology", "518", "Q28", None, None, "Academic Core Microbiology")
_map("Microbiology -- Research methodology", "518.072", "Q28.R4", None, None, "Methodology in Microbiology")
_map("Microbiology -- History and criticism", "518.09", "Q28.H5", None, None, "History of Microbiology")
_map("Microbiology -- Mathematical models", "518.0151", "Q28.M3", None, None, "Mathematical Modeling in Microbiology")
_map("Immunology", "519", "Q29", None, None, "Academic Core Immunology")
_map("Immunology -- Research methodology", "519.072", "Q29.R4", None, None, "Methodology in Immunology")
_map("Immunology -- History and criticism", "519.09", "Q29.H5", None, None, "History of Immunology")
_map("Immunology -- Mathematical models", "519.0151", "Q29.M3", None, None, "Mathematical Modeling in Immunology")
_map("Ecology", "520", "Q30", None, None, "Academic Core Ecology")
_map("Ecology -- Research methodology", "520.072", "Q30.R4", None, None, "Methodology in Ecology")
_map("Ecology -- History and criticism", "520.09", "Q30.H5", None, None, "History of Ecology")
_map("Ecology -- Mathematical models", "520.0151", "Q30.M3", None, None, "Mathematical Modeling in Ecology")
_map("Physiology", "521", "Q31", None, None, "Academic Core Physiology")
_map("Physiology -- Research methodology", "521.072", "Q31.R4", None, None, "Methodology in Physiology")
_map("Physiology -- History and criticism", "521.09", "Q31.H5", None, None, "History of Physiology")
_map("Physiology -- Mathematical models", "521.0151", "Q31.M3", None, None, "Mathematical Modeling in Physiology")
_map("Neuroscience", "522", "Q32", None, None, "Academic Core Neuroscience")
_map("Neuroscience -- Research methodology", "522.072", "Q32.R4", None, None, "Methodology in Neuroscience")
_map("Neuroscience -- History and criticism", "522.09", "Q32.H5", None, None, "History of Neuroscience")
_map("Neuroscience -- Mathematical models", "522.0151", "Q32.M3", None, None, "Mathematical Modeling in Neuroscience")
_map("Botany", "523", "Q33", None, None, "Academic Core Botany")
_map("Botany -- Research methodology", "523.072", "Q33.R4", None, None, "Methodology in Botany")
_map("Botany -- History and criticism", "523.09", "Q33.H5", None, None, "History of Botany")
_map("Botany -- Mathematical models", "523.0151", "Q33.M3", None, None, "Mathematical Modeling in Botany")
_map("Zoology", "524", "Q34", None, None, "Academic Core Zoology")
_map("Zoology -- Research methodology", "524.072", "Q34.R4", None, None, "Methodology in Zoology")
_map("Zoology -- History and criticism", "524.09", "Q34.H5", None, None, "History of Zoology")
_map("Zoology -- Mathematical models", "524.0151", "Q34.M3", None, None, "Mathematical Modeling in Zoology")
_map("Economics", "525", "Q35", None, None, "Academic Core Economics")
_map("Economics -- Research methodology", "525.072", "Q35.R4", None, None, "Methodology in Economics")
_map("Economics -- History and criticism", "525.09", "Q35.H5", None, None, "History of Economics")
_map("Economics -- Mathematical models", "525.0151", "Q35.M3", None, None, "Mathematical Modeling in Economics")
_map("Econometrics", "526", "Q36", None, None, "Academic Core Econometrics")
_map("Econometrics -- Research methodology", "526.072", "Q36.R4", None, None, "Methodology in Econometrics")
_map("Econometrics -- History and criticism", "526.09", "Q36.H5", None, None, "History of Econometrics")
_map("Econometrics -- Mathematical models", "526.0151", "Q36.M3", None, None, "Mathematical Modeling in Econometrics")
_map("Finance", "527", "Q37", None, None, "Academic Core Finance")
_map("Finance -- Research methodology", "527.072", "Q37.R4", None, None, "Methodology in Finance")
_map("Finance -- History and criticism", "527.09", "Q37.H5", None, None, "History of Finance")
_map("Finance -- Mathematical models", "527.0151", "Q37.M3", None, None, "Mathematical Modeling in Finance")
_map("Accounting", "528", "Q38", None, None, "Academic Core Accounting")
_map("Accounting -- Research methodology", "528.072", "Q38.R4", None, None, "Methodology in Accounting")
_map("Accounting -- History and criticism", "528.09", "Q38.H5", None, None, "History of Accounting")
_map("Accounting -- Mathematical models", "528.0151", "Q38.M3", None, None, "Mathematical Modeling in Accounting")
_map("Marketing", "529", "Q39", None, None, "Academic Core Marketing")
_map("Marketing -- Research methodology", "529.072", "Q39.R4", None, None, "Methodology in Marketing")
_map("Marketing -- History and criticism", "529.09", "Q39.H5", None, None, "History of Marketing")
_map("Marketing -- Mathematical models", "529.0151", "Q39.M3", None, None, "Mathematical Modeling in Marketing")
_map("Management", "530", "Q40", None, None, "Academic Core Management")
_map("Management -- Research methodology", "530.072", "Q40.R4", None, None, "Methodology in Management")
_map("Management -- History and criticism", "530.09", "Q40.H5", None, None, "History of Management")
_map("Management -- Mathematical models", "530.0151", "Q40.M3", None, None, "Mathematical Modeling in Management")
_map("Sociology", "531", "Q41", None, None, "Academic Core Sociology")
_map("Sociology -- Research methodology", "531.072", "Q41.R4", None, None, "Methodology in Sociology")
_map("Sociology -- History and criticism", "531.09", "Q41.H5", None, None, "History of Sociology")
_map("Sociology -- Mathematical models", "531.0151", "Q41.M3", None, None, "Mathematical Modeling in Sociology")
_map("Anthropology", "532", "Q42", None, None, "Academic Core Anthropology")
_map("Anthropology -- Research methodology", "532.072", "Q42.R4", None, None, "Methodology in Anthropology")
_map("Anthropology -- History and criticism", "532.09", "Q42.H5", None, None, "History of Anthropology")
_map("Anthropology -- Mathematical models", "532.0151", "Q42.M3", None, None, "Mathematical Modeling in Anthropology")
_map("Archaeology", "533", "Q43", None, None, "Academic Core Archaeology")
_map("Archaeology -- Research methodology", "533.072", "Q43.R4", None, None, "Methodology in Archaeology")
_map("Archaeology -- History and criticism", "533.09", "Q43.H5", None, None, "History of Archaeology")
_map("Archaeology -- Mathematical models", "533.0151", "Q43.M3", None, None, "Mathematical Modeling in Archaeology")
_map("Political science", "534", "Q44", None, None, "Academic Core Political science")
_map("Political science -- Research methodology", "534.072", "Q44.R4", None, None, "Methodology in Political science")
_map("Political science -- History and criticism", "534.09", "Q44.H5", None, None, "History of Political science")
_map("Political science -- Mathematical models", "534.0151", "Q44.M3", None, None, "Mathematical Modeling in Political science")
_map("International relations", "535", "Q45", None, None, "Academic Core International relations")
_map("International relations -- Research methodology", "535.072", "Q45.R4", None, None, "Methodology in International relations")
_map("International relations -- History and criticism", "535.09", "Q45.H5", None, None, "History of International relations")
_map("International relations -- Mathematical models", "535.0151", "Q45.M3", None, None, "Mathematical Modeling in International relations")
_map("Law", "536", "Q46", None, None, "Academic Core Law")
_map("Law -- Research methodology", "536.072", "Q46.R4", None, None, "Methodology in Law")
_map("Law -- History and criticism", "536.09", "Q46.H5", None, None, "History of Law")
_map("Law -- Mathematical models", "536.0151", "Q46.M3", None, None, "Mathematical Modeling in Law")
_map("Philosophy", "537", "Q47", None, None, "Academic Core Philosophy")
_map("Philosophy -- Research methodology", "537.072", "Q47.R4", None, None, "Methodology in Philosophy")
_map("Philosophy -- History and criticism", "537.09", "Q47.H5", None, None, "History of Philosophy")
_map("Philosophy -- Mathematical models", "537.0151", "Q47.M3", None, None, "Mathematical Modeling in Philosophy")
_map("Ethics", "538", "Q48", None, None, "Academic Core Ethics")
_map("Ethics -- Research methodology", "538.072", "Q48.R4", None, None, "Methodology in Ethics")
_map("Ethics -- History and criticism", "538.09", "Q48.H5", None, None, "History of Ethics")
_map("Ethics -- Mathematical models", "538.0151", "Q48.M3", None, None, "Mathematical Modeling in Ethics")
_map("Logic", "539", "Q49", None, None, "Academic Core Logic")
_map("Logic -- Research methodology", "539.072", "Q49.R4", None, None, "Methodology in Logic")
_map("Logic -- History and criticism", "539.09", "Q49.H5", None, None, "History of Logic")
_map("Logic -- Mathematical models", "539.0151", "Q49.M3", None, None, "Mathematical Modeling in Logic")
_map("Epistemology", "540", "Q50", None, None, "Academic Core Epistemology")
_map("Epistemology -- Research methodology", "540.072", "Q50.R4", None, None, "Methodology in Epistemology")
_map("Epistemology -- History and criticism", "540.09", "Q50.H5", None, None, "History of Epistemology")
_map("Epistemology -- Mathematical models", "540.0151", "Q50.M3", None, None, "Mathematical Modeling in Epistemology")
_map("Metaphysics", "541", "Q51", None, None, "Academic Core Metaphysics")
_map("Metaphysics -- Research methodology", "541.072", "Q51.R4", None, None, "Methodology in Metaphysics")
_map("Metaphysics -- History and criticism", "541.09", "Q51.H5", None, None, "History of Metaphysics")
_map("Metaphysics -- Mathematical models", "541.0151", "Q51.M3", None, None, "Mathematical Modeling in Metaphysics")
_map("Aesthetics", "542", "Q52", None, None, "Academic Core Aesthetics")
_map("Aesthetics -- Research methodology", "542.072", "Q52.R4", None, None, "Methodology in Aesthetics")
_map("Aesthetics -- History and criticism", "542.09", "Q52.H5", None, None, "History of Aesthetics")
_map("Aesthetics -- Mathematical models", "542.0151", "Q52.M3", None, None, "Mathematical Modeling in Aesthetics")
_map("History", "543", "Q53", None, None, "Academic Core History")
_map("History -- Research methodology", "543.072", "Q53.R4", None, None, "Methodology in History")
_map("History -- History and criticism", "543.09", "Q53.H5", None, None, "History of History")
_map("History -- Mathematical models", "543.0151", "Q53.M3", None, None, "Mathematical Modeling in History")
_map("Linguistics", "544", "Q54", None, None, "Academic Core Linguistics")
_map("Linguistics -- Research methodology", "544.072", "Q54.R4", None, None, "Methodology in Linguistics")
_map("Linguistics -- History and criticism", "544.09", "Q54.H5", None, None, "History of Linguistics")
_map("Linguistics -- Mathematical models", "544.0151", "Q54.M3", None, None, "Mathematical Modeling in Linguistics")
_map("Literature", "545", "Q55", None, None, "Academic Core Literature")
_map("Literature -- Research methodology", "545.072", "Q55.R4", None, None, "Methodology in Literature")
_map("Literature -- History and criticism", "545.09", "Q55.H5", None, None, "History of Literature")
_map("Literature -- Mathematical models", "545.0151", "Q55.M3", None, None, "Mathematical Modeling in Literature")
_map("Art history", "546", "Q56", None, None, "Academic Core Art history")
_map("Art history -- Research methodology", "546.072", "Q56.R4", None, None, "Methodology in Art history")
_map("Art history -- History and criticism", "546.09", "Q56.H5", None, None, "History of Art history")
_map("Art history -- Mathematical models", "546.0151", "Q56.M3", None, None, "Mathematical Modeling in Art history")
_map("Musicology", "547", "Q57", None, None, "Academic Core Musicology")
_map("Musicology -- Research methodology", "547.072", "Q57.R4", None, None, "Methodology in Musicology")
_map("Musicology -- History and criticism", "547.09", "Q57.H5", None, None, "History of Musicology")
_map("Musicology -- Mathematical models", "547.0151", "Q57.M3", None, None, "Mathematical Modeling in Musicology")
_map("Architecture", "548", "Q58", None, None, "Academic Core Architecture")
_map("Architecture -- Research methodology", "548.072", "Q58.R4", None, None, "Methodology in Architecture")
_map("Architecture -- History and criticism", "548.09", "Q58.H5", None, None, "History of Architecture")
_map("Architecture -- Mathematical models", "548.0151", "Q58.M3", None, None, "Mathematical Modeling in Architecture")

def lookup_classification_for_subject(term: str) -> Optional[ClassificationMapping]:
    return LCSH_TO_CLASSIFICATION_MAP.get(term.strip().lower())
