"""Comprehensive Library Subject Thesaurus and Synonym Expansion Graph.

Enables query expansion and semantic search recall across multi-disciplinary concepts.
"""

from typing import Dict, List, Set, Optional
from dataclasses import dataclass, field


@dataclass
class ThesaurusConcept:
    preferred_label: str
    alternate_labels: List[str] = field(default_factory=list)
    broader_concepts: List[str] = field(default_factory=list)
    narrower_concepts: List[str] = field(default_factory=list)
    related_concepts: List[str] = field(default_factory=list)


THESAURUS_GRAPH: Dict[str, ThesaurusConcept] = {}

def _concept(pref: str, alt: List[str], broader: List[str], narrower: List[str], related: List[str]):
    THESAURUS_GRAPH[pref.lower()] = ThesaurusConcept(pref, alt, broader, narrower, related)

_concept("Computer programming", ['Coding', 'Software development', 'Computer programming languages'], ['Computer science'], ['Functional programming', 'Object-oriented programming', 'Logic programming'], ['Software engineering'])
_concept("Object-oriented programming", ['OOP', 'Object-oriented design'], ['Computer programming'], ['Inheritance', 'Polymorphism', 'Encapsulation'], ['Design patterns'])
_concept("Functional programming", ['Pure functional programming', 'Declarative programming'], ['Computer programming'], ['Lambda calculus', 'Higher-order functions', 'Monads'], ['LISP', 'Haskell'])
_concept("Database management systems", ['DBMS', 'Database software', 'Database engines'], ['Information storage'], ['Relational databases', 'NoSQL databases', 'NewSQL databases'], ['SQL'])
_concept("Relational databases", ['RDBMS', 'SQL databases'], ['Database management systems'], ['PostgreSQL', 'MySQL', 'SQLite', 'Oracle Database'], ['Data normalization'])
_concept("Operating systems", ['OS', 'System software'], ['Computer systems'], ['Linux', 'UNIX', 'Windows', 'macOS', 'Real-time operating systems'], ['Kernel', 'Virtual memory'])
_concept("Computer architecture", ['Hardware architecture', 'Computer organization'], ['Computer engineering'], ['CPU design', 'Instruction set architectures', 'RISC', 'CISC', 'Microprocessors'], ['Computer hardware'])
_concept("Algorithms", ['Computational procedures', 'Algorithmic methods'], ['Computer science', 'Mathematics'], ['Sorting algorithms', 'Search algorithms', 'Graph algorithms', 'Optimization algorithms'], ['Computational complexity'])
_concept("Data structures", ['Information structures', 'Data organization'], ['Computer science'], ['Arrays', 'Linked lists', 'Hash tables', 'Trees (Graph theory)', 'Heaps'], ['Algorithms'])
_concept("Artificial intelligence", ['AI', 'Machine intelligence', 'Synthetic intelligence'], ['Cognitive science', 'Computer science'], ['Machine learning', 'Expert systems', 'Knowledge representation'], ['Robotics', 'Neural networks'])
_concept("Machine learning", ['ML', 'Statistical learning'], ['Artificial intelligence'], ['Supervised learning', 'Unsupervised learning', 'Reinforcement learning'], ['Pattern recognition'])
_concept("Deep learning", ['Deep neural networks', 'Hierarchical feature learning'], ['Machine learning'], ['Convolutional neural networks', 'Recurrent neural networks', 'Transformer models'], ['GPU computing'])
_concept("Natural language processing", ['NLP', 'Computational linguistics', 'Text analytics'], ['Artificial intelligence', 'Linguistics'], ['Machine translation', 'Sentiment analysis', 'Named entity recognition'], ['Information retrieval'])
_concept("Computer vision", ['Machine vision', 'Image understanding'], ['Artificial intelligence'], ['Object detection', 'Image segmentation', 'Facial recognition'], ['Image processing'])
_concept("Cryptography", ['Cryptology', 'Secret writing', 'Information ciphering'], ['Computer security', 'Number theory'], ['Symmetric cryptography', 'Public-key cryptography', 'Cryptographic hashes'], ['Data privacy'])
_concept("Computer networks", ['Data networks', 'Telecommunication networks'], ['Computer engineering'], ['Local area networks', 'Wide area networks', 'Internet', 'Wireless networks'], ['Network protocols'])
_concept("Information security", ['Cybersecurity', 'InfoSec', 'Data protection'], ['Security'], ['Network security', 'Application security', 'Access control', 'Incident response'], ['Vulnerability assessment'])
_concept("Cloud computing", ['Cloud services', 'Elastic computing'], ['Distributed computing'], ['Serverless computing', 'Virtual machines', 'Containers', 'Microservices'], ['DevOps'])
_concept("Software testing", ['Quality assurance', 'Software verification'], ['Software engineering'], ['Unit testing', 'Integration testing', 'System testing', 'Regression testing'], ['Continuous integration'])
_concept("Web development", ['Web programming', 'Web design'], ['Computer programming'], ['Frontend development', 'Backend development', 'Full stack development'], ['HTTP', 'REST APIs'])
_concept("Theoretical Astrophysics", ["Astrophysics (theoretical)"], ["Astrophysics"], [], ["Research methods in Astrophysics"])
_concept("Theoretical Biochemistry", ["Biochemistry (theoretical)"], ["Biochemistry"], [], ["Research methods in Biochemistry"])
_concept("Theoretical Microbiology", ["Microbiology (theoretical)"], ["Microbiology"], [], ["Research methods in Microbiology"])
_concept("Theoretical Ecology", ["Ecology (theoretical)"], ["Ecology"], [], ["Research methods in Ecology"])
_concept("Theoretical Genetics", ["Genetics (theoretical)"], ["Genetics"], [], ["Research methods in Genetics"])
_concept("Theoretical Macroeconomics", ["Macroeconomics (theoretical)"], ["Macroeconomics"], [], ["Research methods in Macroeconomics"])
_concept("Theoretical Microeconomics", ["Microeconomics (theoretical)"], ["Microeconomics"], [], ["Research methods in Microeconomics"])
_concept("Theoretical Econometrics", ["Econometrics (theoretical)"], ["Econometrics"], [], ["Research methods in Econometrics"])
_concept("Theoretical Jurisprudence", ["Jurisprudence (theoretical)"], ["Jurisprudence"], [], ["Research methods in Jurisprudence"])
_concept("Theoretical Sociology", ["Sociology (theoretical)"], ["Sociology"], [], ["Research methods in Sociology"])
_concept("Theoretical Psychology", ["Psychology (theoretical)"], ["Psychology"], [], ["Research methods in Psychology"])
_concept("Theoretical Neuroscience", ["Neuroscience (theoretical)"], ["Neuroscience"], [], ["Research methods in Neuroscience"])
_concept("Theoretical Linguistics", ["Linguistics (theoretical)"], ["Linguistics"], [], ["Research methods in Linguistics"])
_concept("Theoretical Pedagogy", ["Pedagogy (theoretical)"], ["Pedagogy"], [], ["Research methods in Pedagogy"])
_concept("Theoretical Anthropology", ["Anthropology (theoretical)"], ["Anthropology"], [], ["Research methods in Anthropology"])
_concept("Theoretical Archaeology", ["Archaeology (theoretical)"], ["Archaeology"], [], ["Research methods in Archaeology"])
_concept("Theoretical Musicology", ["Musicology (theoretical)"], ["Musicology"], [], ["Research methods in Musicology"])
_concept("Theoretical Cartography", ["Cartography (theoretical)"], ["Cartography"], [], ["Research methods in Cartography"])
_concept("Theoretical Biophysics", ["Biophysics (theoretical)"], ["Biophysics"], [], ["Research methods in Biophysics"])
_concept("Theoretical Nanotechnology", ["Nanotechnology (theoretical)"], ["Nanotechnology"], [], ["Research methods in Nanotechnology"])
_concept("Theoretical Organic Chemistry", ["Organic Chemistry (theoretical)"], ["Organic Chemistry"], [], ["Research methods in Organic Chemistry"])
_concept("Theoretical Inorganic Chemistry", ["Inorganic Chemistry (theoretical)"], ["Inorganic Chemistry"], [], ["Research methods in Inorganic Chemistry"])
_concept("Theoretical Geophysics", ["Geophysics (theoretical)"], ["Geophysics"], [], ["Research methods in Geophysics"])
_concept("Theoretical Meteorology", ["Meteorology (theoretical)"], ["Meteorology"], [], ["Research methods in Meteorology"])
_concept("Theoretical Oceanography", ["Oceanography (theoretical)"], ["Oceanography"], [], ["Research methods in Oceanography"])
_concept("Theoretical Immunology", ["Immunology (theoretical)"], ["Immunology"], [], ["Research methods in Immunology"])
_concept("Theoretical Pharmacology", ["Pharmacology (theoretical)"], ["Pharmacology"], [], ["Research methods in Pharmacology"])
_concept("Theoretical Pathology", ["Pathology (theoretical)"], ["Pathology"], [], ["Research methods in Pathology"])
_concept("Theoretical Virology", ["Virology (theoretical)"], ["Virology"], [], ["Research methods in Virology"])
_concept("Theoretical Cytology", ["Cytology (theoretical)"], ["Cytology"], [], ["Research methods in Cytology"])
_concept("Theoretical Histology", ["Histology (theoretical)"], ["Histology"], [], ["Research methods in Histology"])
_concept("Theoretical Morphology", ["Morphology (theoretical)"], ["Morphology"], [], ["Research methods in Morphology"])
_concept("Theoretical Taxonomy", ["Taxonomy (theoretical)"], ["Taxonomy"], [], ["Research methods in Taxonomy"])
_concept("Theoretical Physiology", ["Physiology (theoretical)"], ["Physiology"], [], ["Research methods in Physiology"])
_concept("Theoretical Endocrinology", ["Endocrinology (theoretical)"], ["Endocrinology"], [], ["Research methods in Endocrinology"])
_concept("Theoretical Cardiology", ["Cardiology (theoretical)"], ["Cardiology"], [], ["Research methods in Cardiology"])
_concept("Theoretical Neurology", ["Neurology (theoretical)"], ["Neurology"], [], ["Research methods in Neurology"])
_concept("Theoretical Oncology", ["Oncology (theoretical)"], ["Oncology"], [], ["Research methods in Oncology"])
_concept("Theoretical Psychiatry", ["Psychiatry (theoretical)"], ["Psychiatry"], [], ["Research methods in Psychiatry"])
_concept("Theoretical Dermatology", ["Dermatology (theoretical)"], ["Dermatology"], [], ["Research methods in Dermatology"])
_concept("Theoretical Epidemiology", ["Epidemiology (theoretical)"], ["Epidemiology"], [], ["Research methods in Epidemiology"])
_concept("Theoretical Toxicology", ["Toxicology (theoretical)"], ["Toxicology"], [], ["Research methods in Toxicology"])
_concept("Theoretical Biotechnology", ["Biotechnology (theoretical)"], ["Biotechnology"], [], ["Research methods in Biotechnology"])
_concept("Theoretical Bioinformatics", ["Bioinformatics (theoretical)"], ["Bioinformatics"], [], ["Research methods in Bioinformatics"])
_concept("Theoretical Genomics", ["Genomics (theoretical)"], ["Genomics"], [], ["Research methods in Genomics"])
_concept("Theoretical Proteomics", ["Proteomics (theoretical)"], ["Proteomics"], [], ["Research methods in Proteomics"])
_concept("Theoretical Bioengineering", ["Bioengineering (theoretical)"], ["Bioengineering"], [], ["Research methods in Bioengineering"])
_concept("Theoretical Biomechanics", ["Biomechanics (theoretical)"], ["Biomechanics"], [], ["Research methods in Biomechanics"])
_concept("Applied Astrophysics", ["Astrophysics (applied)"], ["Astrophysics"], [], ["Research methods in Astrophysics"])
_concept("Applied Biochemistry", ["Biochemistry (applied)"], ["Biochemistry"], [], ["Research methods in Biochemistry"])
_concept("Applied Microbiology", ["Microbiology (applied)"], ["Microbiology"], [], ["Research methods in Microbiology"])
_concept("Applied Ecology", ["Ecology (applied)"], ["Ecology"], [], ["Research methods in Ecology"])
_concept("Applied Genetics", ["Genetics (applied)"], ["Genetics"], [], ["Research methods in Genetics"])
_concept("Applied Macroeconomics", ["Macroeconomics (applied)"], ["Macroeconomics"], [], ["Research methods in Macroeconomics"])
_concept("Applied Microeconomics", ["Microeconomics (applied)"], ["Microeconomics"], [], ["Research methods in Microeconomics"])
_concept("Applied Econometrics", ["Econometrics (applied)"], ["Econometrics"], [], ["Research methods in Econometrics"])
_concept("Applied Jurisprudence", ["Jurisprudence (applied)"], ["Jurisprudence"], [], ["Research methods in Jurisprudence"])
_concept("Applied Sociology", ["Sociology (applied)"], ["Sociology"], [], ["Research methods in Sociology"])
_concept("Applied Psychology", ["Psychology (applied)"], ["Psychology"], [], ["Research methods in Psychology"])
_concept("Applied Neuroscience", ["Neuroscience (applied)"], ["Neuroscience"], [], ["Research methods in Neuroscience"])
_concept("Applied Linguistics", ["Linguistics (applied)"], ["Linguistics"], [], ["Research methods in Linguistics"])
_concept("Applied Pedagogy", ["Pedagogy (applied)"], ["Pedagogy"], [], ["Research methods in Pedagogy"])
_concept("Applied Anthropology", ["Anthropology (applied)"], ["Anthropology"], [], ["Research methods in Anthropology"])
_concept("Applied Archaeology", ["Archaeology (applied)"], ["Archaeology"], [], ["Research methods in Archaeology"])
_concept("Applied Musicology", ["Musicology (applied)"], ["Musicology"], [], ["Research methods in Musicology"])
_concept("Applied Cartography", ["Cartography (applied)"], ["Cartography"], [], ["Research methods in Cartography"])
_concept("Applied Biophysics", ["Biophysics (applied)"], ["Biophysics"], [], ["Research methods in Biophysics"])
_concept("Applied Nanotechnology", ["Nanotechnology (applied)"], ["Nanotechnology"], [], ["Research methods in Nanotechnology"])
_concept("Applied Organic Chemistry", ["Organic Chemistry (applied)"], ["Organic Chemistry"], [], ["Research methods in Organic Chemistry"])
_concept("Applied Inorganic Chemistry", ["Inorganic Chemistry (applied)"], ["Inorganic Chemistry"], [], ["Research methods in Inorganic Chemistry"])
_concept("Applied Geophysics", ["Geophysics (applied)"], ["Geophysics"], [], ["Research methods in Geophysics"])
_concept("Applied Meteorology", ["Meteorology (applied)"], ["Meteorology"], [], ["Research methods in Meteorology"])
_concept("Applied Oceanography", ["Oceanography (applied)"], ["Oceanography"], [], ["Research methods in Oceanography"])
_concept("Applied Immunology", ["Immunology (applied)"], ["Immunology"], [], ["Research methods in Immunology"])
_concept("Applied Pharmacology", ["Pharmacology (applied)"], ["Pharmacology"], [], ["Research methods in Pharmacology"])
_concept("Applied Pathology", ["Pathology (applied)"], ["Pathology"], [], ["Research methods in Pathology"])
_concept("Applied Virology", ["Virology (applied)"], ["Virology"], [], ["Research methods in Virology"])
_concept("Applied Cytology", ["Cytology (applied)"], ["Cytology"], [], ["Research methods in Cytology"])
_concept("Applied Histology", ["Histology (applied)"], ["Histology"], [], ["Research methods in Histology"])
_concept("Applied Morphology", ["Morphology (applied)"], ["Morphology"], [], ["Research methods in Morphology"])
_concept("Applied Taxonomy", ["Taxonomy (applied)"], ["Taxonomy"], [], ["Research methods in Taxonomy"])
_concept("Applied Physiology", ["Physiology (applied)"], ["Physiology"], [], ["Research methods in Physiology"])
_concept("Applied Endocrinology", ["Endocrinology (applied)"], ["Endocrinology"], [], ["Research methods in Endocrinology"])
_concept("Applied Cardiology", ["Cardiology (applied)"], ["Cardiology"], [], ["Research methods in Cardiology"])
_concept("Applied Neurology", ["Neurology (applied)"], ["Neurology"], [], ["Research methods in Neurology"])
_concept("Applied Oncology", ["Oncology (applied)"], ["Oncology"], [], ["Research methods in Oncology"])
_concept("Applied Psychiatry", ["Psychiatry (applied)"], ["Psychiatry"], [], ["Research methods in Psychiatry"])
_concept("Applied Dermatology", ["Dermatology (applied)"], ["Dermatology"], [], ["Research methods in Dermatology"])
_concept("Applied Epidemiology", ["Epidemiology (applied)"], ["Epidemiology"], [], ["Research methods in Epidemiology"])
_concept("Applied Toxicology", ["Toxicology (applied)"], ["Toxicology"], [], ["Research methods in Toxicology"])
_concept("Applied Biotechnology", ["Biotechnology (applied)"], ["Biotechnology"], [], ["Research methods in Biotechnology"])
_concept("Applied Bioinformatics", ["Bioinformatics (applied)"], ["Bioinformatics"], [], ["Research methods in Bioinformatics"])
_concept("Applied Genomics", ["Genomics (applied)"], ["Genomics"], [], ["Research methods in Genomics"])
_concept("Applied Proteomics", ["Proteomics (applied)"], ["Proteomics"], [], ["Research methods in Proteomics"])
_concept("Applied Bioengineering", ["Bioengineering (applied)"], ["Bioengineering"], [], ["Research methods in Bioengineering"])
_concept("Applied Biomechanics", ["Biomechanics (applied)"], ["Biomechanics"], [], ["Research methods in Biomechanics"])
_concept("Computational Astrophysics", ["Astrophysics (computational)"], ["Astrophysics"], [], ["Research methods in Astrophysics"])
_concept("Computational Biochemistry", ["Biochemistry (computational)"], ["Biochemistry"], [], ["Research methods in Biochemistry"])
_concept("Computational Microbiology", ["Microbiology (computational)"], ["Microbiology"], [], ["Research methods in Microbiology"])
_concept("Computational Ecology", ["Ecology (computational)"], ["Ecology"], [], ["Research methods in Ecology"])
_concept("Computational Genetics", ["Genetics (computational)"], ["Genetics"], [], ["Research methods in Genetics"])
_concept("Computational Macroeconomics", ["Macroeconomics (computational)"], ["Macroeconomics"], [], ["Research methods in Macroeconomics"])
_concept("Computational Microeconomics", ["Microeconomics (computational)"], ["Microeconomics"], [], ["Research methods in Microeconomics"])
_concept("Computational Econometrics", ["Econometrics (computational)"], ["Econometrics"], [], ["Research methods in Econometrics"])
_concept("Computational Jurisprudence", ["Jurisprudence (computational)"], ["Jurisprudence"], [], ["Research methods in Jurisprudence"])
_concept("Computational Sociology", ["Sociology (computational)"], ["Sociology"], [], ["Research methods in Sociology"])
_concept("Computational Psychology", ["Psychology (computational)"], ["Psychology"], [], ["Research methods in Psychology"])
_concept("Computational Neuroscience", ["Neuroscience (computational)"], ["Neuroscience"], [], ["Research methods in Neuroscience"])
_concept("Computational Linguistics", ["Linguistics (computational)"], ["Linguistics"], [], ["Research methods in Linguistics"])
_concept("Computational Pedagogy", ["Pedagogy (computational)"], ["Pedagogy"], [], ["Research methods in Pedagogy"])
_concept("Computational Anthropology", ["Anthropology (computational)"], ["Anthropology"], [], ["Research methods in Anthropology"])
_concept("Computational Archaeology", ["Archaeology (computational)"], ["Archaeology"], [], ["Research methods in Archaeology"])
_concept("Computational Musicology", ["Musicology (computational)"], ["Musicology"], [], ["Research methods in Musicology"])
_concept("Computational Cartography", ["Cartography (computational)"], ["Cartography"], [], ["Research methods in Cartography"])
_concept("Computational Biophysics", ["Biophysics (computational)"], ["Biophysics"], [], ["Research methods in Biophysics"])
_concept("Computational Nanotechnology", ["Nanotechnology (computational)"], ["Nanotechnology"], [], ["Research methods in Nanotechnology"])
_concept("Computational Organic Chemistry", ["Organic Chemistry (computational)"], ["Organic Chemistry"], [], ["Research methods in Organic Chemistry"])
_concept("Computational Inorganic Chemistry", ["Inorganic Chemistry (computational)"], ["Inorganic Chemistry"], [], ["Research methods in Inorganic Chemistry"])
_concept("Computational Geophysics", ["Geophysics (computational)"], ["Geophysics"], [], ["Research methods in Geophysics"])
_concept("Computational Meteorology", ["Meteorology (computational)"], ["Meteorology"], [], ["Research methods in Meteorology"])
_concept("Computational Oceanography", ["Oceanography (computational)"], ["Oceanography"], [], ["Research methods in Oceanography"])
_concept("Computational Immunology", ["Immunology (computational)"], ["Immunology"], [], ["Research methods in Immunology"])
_concept("Computational Pharmacology", ["Pharmacology (computational)"], ["Pharmacology"], [], ["Research methods in Pharmacology"])
_concept("Computational Pathology", ["Pathology (computational)"], ["Pathology"], [], ["Research methods in Pathology"])
_concept("Computational Virology", ["Virology (computational)"], ["Virology"], [], ["Research methods in Virology"])
_concept("Computational Cytology", ["Cytology (computational)"], ["Cytology"], [], ["Research methods in Cytology"])
_concept("Computational Histology", ["Histology (computational)"], ["Histology"], [], ["Research methods in Histology"])
_concept("Computational Morphology", ["Morphology (computational)"], ["Morphology"], [], ["Research methods in Morphology"])
_concept("Computational Taxonomy", ["Taxonomy (computational)"], ["Taxonomy"], [], ["Research methods in Taxonomy"])
_concept("Computational Physiology", ["Physiology (computational)"], ["Physiology"], [], ["Research methods in Physiology"])
_concept("Computational Endocrinology", ["Endocrinology (computational)"], ["Endocrinology"], [], ["Research methods in Endocrinology"])
_concept("Computational Cardiology", ["Cardiology (computational)"], ["Cardiology"], [], ["Research methods in Cardiology"])
_concept("Computational Neurology", ["Neurology (computational)"], ["Neurology"], [], ["Research methods in Neurology"])
_concept("Computational Oncology", ["Oncology (computational)"], ["Oncology"], [], ["Research methods in Oncology"])
_concept("Computational Psychiatry", ["Psychiatry (computational)"], ["Psychiatry"], [], ["Research methods in Psychiatry"])
_concept("Computational Dermatology", ["Dermatology (computational)"], ["Dermatology"], [], ["Research methods in Dermatology"])
_concept("Computational Epidemiology", ["Epidemiology (computational)"], ["Epidemiology"], [], ["Research methods in Epidemiology"])
_concept("Computational Toxicology", ["Toxicology (computational)"], ["Toxicology"], [], ["Research methods in Toxicology"])
_concept("Computational Biotechnology", ["Biotechnology (computational)"], ["Biotechnology"], [], ["Research methods in Biotechnology"])
_concept("Computational Bioinformatics", ["Bioinformatics (computational)"], ["Bioinformatics"], [], ["Research methods in Bioinformatics"])
_concept("Computational Genomics", ["Genomics (computational)"], ["Genomics"], [], ["Research methods in Genomics"])
_concept("Computational Proteomics", ["Proteomics (computational)"], ["Proteomics"], [], ["Research methods in Proteomics"])
_concept("Computational Bioengineering", ["Bioengineering (computational)"], ["Bioengineering"], [], ["Research methods in Bioengineering"])
_concept("Computational Biomechanics", ["Biomechanics (computational)"], ["Biomechanics"], [], ["Research methods in Biomechanics"])
_concept("Experimental Astrophysics", ["Astrophysics (experimental)"], ["Astrophysics"], [], ["Research methods in Astrophysics"])
_concept("Experimental Biochemistry", ["Biochemistry (experimental)"], ["Biochemistry"], [], ["Research methods in Biochemistry"])
_concept("Experimental Microbiology", ["Microbiology (experimental)"], ["Microbiology"], [], ["Research methods in Microbiology"])
_concept("Experimental Ecology", ["Ecology (experimental)"], ["Ecology"], [], ["Research methods in Ecology"])
_concept("Experimental Genetics", ["Genetics (experimental)"], ["Genetics"], [], ["Research methods in Genetics"])
_concept("Experimental Macroeconomics", ["Macroeconomics (experimental)"], ["Macroeconomics"], [], ["Research methods in Macroeconomics"])
_concept("Experimental Microeconomics", ["Microeconomics (experimental)"], ["Microeconomics"], [], ["Research methods in Microeconomics"])
_concept("Experimental Econometrics", ["Econometrics (experimental)"], ["Econometrics"], [], ["Research methods in Econometrics"])
_concept("Experimental Jurisprudence", ["Jurisprudence (experimental)"], ["Jurisprudence"], [], ["Research methods in Jurisprudence"])
_concept("Experimental Sociology", ["Sociology (experimental)"], ["Sociology"], [], ["Research methods in Sociology"])
_concept("Experimental Psychology", ["Psychology (experimental)"], ["Psychology"], [], ["Research methods in Psychology"])
_concept("Experimental Neuroscience", ["Neuroscience (experimental)"], ["Neuroscience"], [], ["Research methods in Neuroscience"])
_concept("Experimental Linguistics", ["Linguistics (experimental)"], ["Linguistics"], [], ["Research methods in Linguistics"])
_concept("Experimental Pedagogy", ["Pedagogy (experimental)"], ["Pedagogy"], [], ["Research methods in Pedagogy"])
_concept("Experimental Anthropology", ["Anthropology (experimental)"], ["Anthropology"], [], ["Research methods in Anthropology"])
_concept("Experimental Archaeology", ["Archaeology (experimental)"], ["Archaeology"], [], ["Research methods in Archaeology"])
_concept("Experimental Musicology", ["Musicology (experimental)"], ["Musicology"], [], ["Research methods in Musicology"])
_concept("Experimental Cartography", ["Cartography (experimental)"], ["Cartography"], [], ["Research methods in Cartography"])
_concept("Experimental Biophysics", ["Biophysics (experimental)"], ["Biophysics"], [], ["Research methods in Biophysics"])
_concept("Experimental Nanotechnology", ["Nanotechnology (experimental)"], ["Nanotechnology"], [], ["Research methods in Nanotechnology"])
_concept("Experimental Organic Chemistry", ["Organic Chemistry (experimental)"], ["Organic Chemistry"], [], ["Research methods in Organic Chemistry"])
_concept("Experimental Inorganic Chemistry", ["Inorganic Chemistry (experimental)"], ["Inorganic Chemistry"], [], ["Research methods in Inorganic Chemistry"])
_concept("Experimental Geophysics", ["Geophysics (experimental)"], ["Geophysics"], [], ["Research methods in Geophysics"])
_concept("Experimental Meteorology", ["Meteorology (experimental)"], ["Meteorology"], [], ["Research methods in Meteorology"])
_concept("Experimental Oceanography", ["Oceanography (experimental)"], ["Oceanography"], [], ["Research methods in Oceanography"])
_concept("Experimental Immunology", ["Immunology (experimental)"], ["Immunology"], [], ["Research methods in Immunology"])
_concept("Experimental Pharmacology", ["Pharmacology (experimental)"], ["Pharmacology"], [], ["Research methods in Pharmacology"])
_concept("Experimental Pathology", ["Pathology (experimental)"], ["Pathology"], [], ["Research methods in Pathology"])
_concept("Experimental Virology", ["Virology (experimental)"], ["Virology"], [], ["Research methods in Virology"])
_concept("Experimental Cytology", ["Cytology (experimental)"], ["Cytology"], [], ["Research methods in Cytology"])
_concept("Experimental Histology", ["Histology (experimental)"], ["Histology"], [], ["Research methods in Histology"])
_concept("Experimental Morphology", ["Morphology (experimental)"], ["Morphology"], [], ["Research methods in Morphology"])
_concept("Experimental Taxonomy", ["Taxonomy (experimental)"], ["Taxonomy"], [], ["Research methods in Taxonomy"])
_concept("Experimental Physiology", ["Physiology (experimental)"], ["Physiology"], [], ["Research methods in Physiology"])
_concept("Experimental Endocrinology", ["Endocrinology (experimental)"], ["Endocrinology"], [], ["Research methods in Endocrinology"])
_concept("Experimental Cardiology", ["Cardiology (experimental)"], ["Cardiology"], [], ["Research methods in Cardiology"])
_concept("Experimental Neurology", ["Neurology (experimental)"], ["Neurology"], [], ["Research methods in Neurology"])
_concept("Experimental Oncology", ["Oncology (experimental)"], ["Oncology"], [], ["Research methods in Oncology"])
_concept("Experimental Psychiatry", ["Psychiatry (experimental)"], ["Psychiatry"], [], ["Research methods in Psychiatry"])
_concept("Experimental Dermatology", ["Dermatology (experimental)"], ["Dermatology"], [], ["Research methods in Dermatology"])
_concept("Experimental Epidemiology", ["Epidemiology (experimental)"], ["Epidemiology"], [], ["Research methods in Epidemiology"])
_concept("Experimental Toxicology", ["Toxicology (experimental)"], ["Toxicology"], [], ["Research methods in Toxicology"])
_concept("Experimental Biotechnology", ["Biotechnology (experimental)"], ["Biotechnology"], [], ["Research methods in Biotechnology"])
_concept("Experimental Bioinformatics", ["Bioinformatics (experimental)"], ["Bioinformatics"], [], ["Research methods in Bioinformatics"])
_concept("Experimental Genomics", ["Genomics (experimental)"], ["Genomics"], [], ["Research methods in Genomics"])
_concept("Experimental Proteomics", ["Proteomics (experimental)"], ["Proteomics"], [], ["Research methods in Proteomics"])
_concept("Experimental Bioengineering", ["Bioengineering (experimental)"], ["Bioengineering"], [], ["Research methods in Bioengineering"])
_concept("Experimental Biomechanics", ["Biomechanics (experimental)"], ["Biomechanics"], [], ["Research methods in Biomechanics"])
_concept("Industrial Astrophysics", ["Astrophysics (industrial)"], ["Astrophysics"], [], ["Research methods in Astrophysics"])
_concept("Industrial Biochemistry", ["Biochemistry (industrial)"], ["Biochemistry"], [], ["Research methods in Biochemistry"])
_concept("Industrial Microbiology", ["Microbiology (industrial)"], ["Microbiology"], [], ["Research methods in Microbiology"])
_concept("Industrial Ecology", ["Ecology (industrial)"], ["Ecology"], [], ["Research methods in Ecology"])
_concept("Industrial Genetics", ["Genetics (industrial)"], ["Genetics"], [], ["Research methods in Genetics"])
_concept("Industrial Macroeconomics", ["Macroeconomics (industrial)"], ["Macroeconomics"], [], ["Research methods in Macroeconomics"])
_concept("Industrial Microeconomics", ["Microeconomics (industrial)"], ["Microeconomics"], [], ["Research methods in Microeconomics"])
_concept("Industrial Econometrics", ["Econometrics (industrial)"], ["Econometrics"], [], ["Research methods in Econometrics"])
_concept("Industrial Jurisprudence", ["Jurisprudence (industrial)"], ["Jurisprudence"], [], ["Research methods in Jurisprudence"])
_concept("Industrial Sociology", ["Sociology (industrial)"], ["Sociology"], [], ["Research methods in Sociology"])
_concept("Industrial Psychology", ["Psychology (industrial)"], ["Psychology"], [], ["Research methods in Psychology"])
_concept("Industrial Neuroscience", ["Neuroscience (industrial)"], ["Neuroscience"], [], ["Research methods in Neuroscience"])
_concept("Industrial Linguistics", ["Linguistics (industrial)"], ["Linguistics"], [], ["Research methods in Linguistics"])
_concept("Industrial Pedagogy", ["Pedagogy (industrial)"], ["Pedagogy"], [], ["Research methods in Pedagogy"])
_concept("Industrial Anthropology", ["Anthropology (industrial)"], ["Anthropology"], [], ["Research methods in Anthropology"])
_concept("Industrial Archaeology", ["Archaeology (industrial)"], ["Archaeology"], [], ["Research methods in Archaeology"])
_concept("Industrial Musicology", ["Musicology (industrial)"], ["Musicology"], [], ["Research methods in Musicology"])
_concept("Industrial Cartography", ["Cartography (industrial)"], ["Cartography"], [], ["Research methods in Cartography"])
_concept("Industrial Biophysics", ["Biophysics (industrial)"], ["Biophysics"], [], ["Research methods in Biophysics"])
_concept("Industrial Nanotechnology", ["Nanotechnology (industrial)"], ["Nanotechnology"], [], ["Research methods in Nanotechnology"])
_concept("Industrial Organic Chemistry", ["Organic Chemistry (industrial)"], ["Organic Chemistry"], [], ["Research methods in Organic Chemistry"])
_concept("Industrial Inorganic Chemistry", ["Inorganic Chemistry (industrial)"], ["Inorganic Chemistry"], [], ["Research methods in Inorganic Chemistry"])
_concept("Industrial Geophysics", ["Geophysics (industrial)"], ["Geophysics"], [], ["Research methods in Geophysics"])
_concept("Industrial Meteorology", ["Meteorology (industrial)"], ["Meteorology"], [], ["Research methods in Meteorology"])
_concept("Industrial Oceanography", ["Oceanography (industrial)"], ["Oceanography"], [], ["Research methods in Oceanography"])
_concept("Industrial Immunology", ["Immunology (industrial)"], ["Immunology"], [], ["Research methods in Immunology"])
_concept("Industrial Pharmacology", ["Pharmacology (industrial)"], ["Pharmacology"], [], ["Research methods in Pharmacology"])
_concept("Industrial Pathology", ["Pathology (industrial)"], ["Pathology"], [], ["Research methods in Pathology"])
_concept("Industrial Virology", ["Virology (industrial)"], ["Virology"], [], ["Research methods in Virology"])
_concept("Industrial Cytology", ["Cytology (industrial)"], ["Cytology"], [], ["Research methods in Cytology"])
_concept("Industrial Histology", ["Histology (industrial)"], ["Histology"], [], ["Research methods in Histology"])
_concept("Industrial Morphology", ["Morphology (industrial)"], ["Morphology"], [], ["Research methods in Morphology"])
_concept("Industrial Taxonomy", ["Taxonomy (industrial)"], ["Taxonomy"], [], ["Research methods in Taxonomy"])
_concept("Industrial Physiology", ["Physiology (industrial)"], ["Physiology"], [], ["Research methods in Physiology"])
_concept("Industrial Endocrinology", ["Endocrinology (industrial)"], ["Endocrinology"], [], ["Research methods in Endocrinology"])
_concept("Industrial Cardiology", ["Cardiology (industrial)"], ["Cardiology"], [], ["Research methods in Cardiology"])
_concept("Industrial Neurology", ["Neurology (industrial)"], ["Neurology"], [], ["Research methods in Neurology"])
_concept("Industrial Oncology", ["Oncology (industrial)"], ["Oncology"], [], ["Research methods in Oncology"])
_concept("Industrial Psychiatry", ["Psychiatry (industrial)"], ["Psychiatry"], [], ["Research methods in Psychiatry"])
_concept("Industrial Dermatology", ["Dermatology (industrial)"], ["Dermatology"], [], ["Research methods in Dermatology"])
_concept("Industrial Epidemiology", ["Epidemiology (industrial)"], ["Epidemiology"], [], ["Research methods in Epidemiology"])
_concept("Industrial Toxicology", ["Toxicology (industrial)"], ["Toxicology"], [], ["Research methods in Toxicology"])
_concept("Industrial Biotechnology", ["Biotechnology (industrial)"], ["Biotechnology"], [], ["Research methods in Biotechnology"])
_concept("Industrial Bioinformatics", ["Bioinformatics (industrial)"], ["Bioinformatics"], [], ["Research methods in Bioinformatics"])
_concept("Industrial Genomics", ["Genomics (industrial)"], ["Genomics"], [], ["Research methods in Genomics"])
_concept("Industrial Proteomics", ["Proteomics (industrial)"], ["Proteomics"], [], ["Research methods in Proteomics"])
_concept("Industrial Bioengineering", ["Bioengineering (industrial)"], ["Bioengineering"], [], ["Research methods in Bioengineering"])
_concept("Industrial Biomechanics", ["Biomechanics (industrial)"], ["Biomechanics"], [], ["Research methods in Biomechanics"])
_concept("Advanced Astrophysics", ["Astrophysics (advanced)"], ["Astrophysics"], [], ["Research methods in Astrophysics"])
_concept("Advanced Biochemistry", ["Biochemistry (advanced)"], ["Biochemistry"], [], ["Research methods in Biochemistry"])
_concept("Advanced Microbiology", ["Microbiology (advanced)"], ["Microbiology"], [], ["Research methods in Microbiology"])
_concept("Advanced Ecology", ["Ecology (advanced)"], ["Ecology"], [], ["Research methods in Ecology"])
_concept("Advanced Genetics", ["Genetics (advanced)"], ["Genetics"], [], ["Research methods in Genetics"])
_concept("Advanced Macroeconomics", ["Macroeconomics (advanced)"], ["Macroeconomics"], [], ["Research methods in Macroeconomics"])
_concept("Advanced Microeconomics", ["Microeconomics (advanced)"], ["Microeconomics"], [], ["Research methods in Microeconomics"])
_concept("Advanced Econometrics", ["Econometrics (advanced)"], ["Econometrics"], [], ["Research methods in Econometrics"])
_concept("Advanced Jurisprudence", ["Jurisprudence (advanced)"], ["Jurisprudence"], [], ["Research methods in Jurisprudence"])
_concept("Advanced Sociology", ["Sociology (advanced)"], ["Sociology"], [], ["Research methods in Sociology"])
_concept("Advanced Psychology", ["Psychology (advanced)"], ["Psychology"], [], ["Research methods in Psychology"])
_concept("Advanced Neuroscience", ["Neuroscience (advanced)"], ["Neuroscience"], [], ["Research methods in Neuroscience"])
_concept("Advanced Linguistics", ["Linguistics (advanced)"], ["Linguistics"], [], ["Research methods in Linguistics"])
_concept("Advanced Pedagogy", ["Pedagogy (advanced)"], ["Pedagogy"], [], ["Research methods in Pedagogy"])
_concept("Advanced Anthropology", ["Anthropology (advanced)"], ["Anthropology"], [], ["Research methods in Anthropology"])
_concept("Advanced Archaeology", ["Archaeology (advanced)"], ["Archaeology"], [], ["Research methods in Archaeology"])
_concept("Advanced Musicology", ["Musicology (advanced)"], ["Musicology"], [], ["Research methods in Musicology"])
_concept("Advanced Cartography", ["Cartography (advanced)"], ["Cartography"], [], ["Research methods in Cartography"])
_concept("Advanced Biophysics", ["Biophysics (advanced)"], ["Biophysics"], [], ["Research methods in Biophysics"])
_concept("Advanced Nanotechnology", ["Nanotechnology (advanced)"], ["Nanotechnology"], [], ["Research methods in Nanotechnology"])
_concept("Advanced Organic Chemistry", ["Organic Chemistry (advanced)"], ["Organic Chemistry"], [], ["Research methods in Organic Chemistry"])
_concept("Advanced Inorganic Chemistry", ["Inorganic Chemistry (advanced)"], ["Inorganic Chemistry"], [], ["Research methods in Inorganic Chemistry"])
_concept("Advanced Geophysics", ["Geophysics (advanced)"], ["Geophysics"], [], ["Research methods in Geophysics"])
_concept("Advanced Meteorology", ["Meteorology (advanced)"], ["Meteorology"], [], ["Research methods in Meteorology"])
_concept("Advanced Oceanography", ["Oceanography (advanced)"], ["Oceanography"], [], ["Research methods in Oceanography"])
_concept("Advanced Immunology", ["Immunology (advanced)"], ["Immunology"], [], ["Research methods in Immunology"])
_concept("Advanced Pharmacology", ["Pharmacology (advanced)"], ["Pharmacology"], [], ["Research methods in Pharmacology"])
_concept("Advanced Pathology", ["Pathology (advanced)"], ["Pathology"], [], ["Research methods in Pathology"])
_concept("Advanced Virology", ["Virology (advanced)"], ["Virology"], [], ["Research methods in Virology"])
_concept("Advanced Cytology", ["Cytology (advanced)"], ["Cytology"], [], ["Research methods in Cytology"])
_concept("Advanced Histology", ["Histology (advanced)"], ["Histology"], [], ["Research methods in Histology"])
_concept("Advanced Morphology", ["Morphology (advanced)"], ["Morphology"], [], ["Research methods in Morphology"])
_concept("Advanced Taxonomy", ["Taxonomy (advanced)"], ["Taxonomy"], [], ["Research methods in Taxonomy"])
_concept("Advanced Physiology", ["Physiology (advanced)"], ["Physiology"], [], ["Research methods in Physiology"])
_concept("Advanced Endocrinology", ["Endocrinology (advanced)"], ["Endocrinology"], [], ["Research methods in Endocrinology"])
_concept("Advanced Cardiology", ["Cardiology (advanced)"], ["Cardiology"], [], ["Research methods in Cardiology"])
_concept("Advanced Neurology", ["Neurology (advanced)"], ["Neurology"], [], ["Research methods in Neurology"])
_concept("Advanced Oncology", ["Oncology (advanced)"], ["Oncology"], [], ["Research methods in Oncology"])
_concept("Advanced Psychiatry", ["Psychiatry (advanced)"], ["Psychiatry"], [], ["Research methods in Psychiatry"])
_concept("Advanced Dermatology", ["Dermatology (advanced)"], ["Dermatology"], [], ["Research methods in Dermatology"])
_concept("Advanced Epidemiology", ["Epidemiology (advanced)"], ["Epidemiology"], [], ["Research methods in Epidemiology"])
_concept("Advanced Toxicology", ["Toxicology (advanced)"], ["Toxicology"], [], ["Research methods in Toxicology"])
_concept("Advanced Biotechnology", ["Biotechnology (advanced)"], ["Biotechnology"], [], ["Research methods in Biotechnology"])
_concept("Advanced Bioinformatics", ["Bioinformatics (advanced)"], ["Bioinformatics"], [], ["Research methods in Bioinformatics"])
_concept("Advanced Genomics", ["Genomics (advanced)"], ["Genomics"], [], ["Research methods in Genomics"])
_concept("Advanced Proteomics", ["Proteomics (advanced)"], ["Proteomics"], [], ["Research methods in Proteomics"])
_concept("Advanced Bioengineering", ["Bioengineering (advanced)"], ["Bioengineering"], [], ["Research methods in Bioengineering"])
_concept("Advanced Biomechanics", ["Biomechanics (advanced)"], ["Biomechanics"], [], ["Research methods in Biomechanics"])
_concept("Fundamental Astrophysics", ["Astrophysics (fundamental)"], ["Astrophysics"], [], ["Research methods in Astrophysics"])
_concept("Fundamental Biochemistry", ["Biochemistry (fundamental)"], ["Biochemistry"], [], ["Research methods in Biochemistry"])
_concept("Fundamental Microbiology", ["Microbiology (fundamental)"], ["Microbiology"], [], ["Research methods in Microbiology"])
_concept("Fundamental Ecology", ["Ecology (fundamental)"], ["Ecology"], [], ["Research methods in Ecology"])
_concept("Fundamental Genetics", ["Genetics (fundamental)"], ["Genetics"], [], ["Research methods in Genetics"])
_concept("Fundamental Macroeconomics", ["Macroeconomics (fundamental)"], ["Macroeconomics"], [], ["Research methods in Macroeconomics"])
_concept("Fundamental Microeconomics", ["Microeconomics (fundamental)"], ["Microeconomics"], [], ["Research methods in Microeconomics"])
_concept("Fundamental Econometrics", ["Econometrics (fundamental)"], ["Econometrics"], [], ["Research methods in Econometrics"])
_concept("Fundamental Jurisprudence", ["Jurisprudence (fundamental)"], ["Jurisprudence"], [], ["Research methods in Jurisprudence"])
_concept("Fundamental Sociology", ["Sociology (fundamental)"], ["Sociology"], [], ["Research methods in Sociology"])
_concept("Fundamental Psychology", ["Psychology (fundamental)"], ["Psychology"], [], ["Research methods in Psychology"])
_concept("Fundamental Neuroscience", ["Neuroscience (fundamental)"], ["Neuroscience"], [], ["Research methods in Neuroscience"])
_concept("Fundamental Linguistics", ["Linguistics (fundamental)"], ["Linguistics"], [], ["Research methods in Linguistics"])
_concept("Fundamental Pedagogy", ["Pedagogy (fundamental)"], ["Pedagogy"], [], ["Research methods in Pedagogy"])
_concept("Fundamental Anthropology", ["Anthropology (fundamental)"], ["Anthropology"], [], ["Research methods in Anthropology"])
_concept("Fundamental Archaeology", ["Archaeology (fundamental)"], ["Archaeology"], [], ["Research methods in Archaeology"])
_concept("Fundamental Musicology", ["Musicology (fundamental)"], ["Musicology"], [], ["Research methods in Musicology"])
_concept("Fundamental Cartography", ["Cartography (fundamental)"], ["Cartography"], [], ["Research methods in Cartography"])
_concept("Fundamental Biophysics", ["Biophysics (fundamental)"], ["Biophysics"], [], ["Research methods in Biophysics"])
_concept("Fundamental Nanotechnology", ["Nanotechnology (fundamental)"], ["Nanotechnology"], [], ["Research methods in Nanotechnology"])
_concept("Fundamental Organic Chemistry", ["Organic Chemistry (fundamental)"], ["Organic Chemistry"], [], ["Research methods in Organic Chemistry"])
_concept("Fundamental Inorganic Chemistry", ["Inorganic Chemistry (fundamental)"], ["Inorganic Chemistry"], [], ["Research methods in Inorganic Chemistry"])
_concept("Fundamental Geophysics", ["Geophysics (fundamental)"], ["Geophysics"], [], ["Research methods in Geophysics"])
_concept("Fundamental Meteorology", ["Meteorology (fundamental)"], ["Meteorology"], [], ["Research methods in Meteorology"])
_concept("Fundamental Oceanography", ["Oceanography (fundamental)"], ["Oceanography"], [], ["Research methods in Oceanography"])
_concept("Fundamental Immunology", ["Immunology (fundamental)"], ["Immunology"], [], ["Research methods in Immunology"])
_concept("Fundamental Pharmacology", ["Pharmacology (fundamental)"], ["Pharmacology"], [], ["Research methods in Pharmacology"])
_concept("Fundamental Pathology", ["Pathology (fundamental)"], ["Pathology"], [], ["Research methods in Pathology"])
_concept("Fundamental Virology", ["Virology (fundamental)"], ["Virology"], [], ["Research methods in Virology"])
_concept("Fundamental Cytology", ["Cytology (fundamental)"], ["Cytology"], [], ["Research methods in Cytology"])
_concept("Fundamental Histology", ["Histology (fundamental)"], ["Histology"], [], ["Research methods in Histology"])
_concept("Fundamental Morphology", ["Morphology (fundamental)"], ["Morphology"], [], ["Research methods in Morphology"])
_concept("Fundamental Taxonomy", ["Taxonomy (fundamental)"], ["Taxonomy"], [], ["Research methods in Taxonomy"])
_concept("Fundamental Physiology", ["Physiology (fundamental)"], ["Physiology"], [], ["Research methods in Physiology"])
_concept("Fundamental Endocrinology", ["Endocrinology (fundamental)"], ["Endocrinology"], [], ["Research methods in Endocrinology"])
_concept("Fundamental Cardiology", ["Cardiology (fundamental)"], ["Cardiology"], [], ["Research methods in Cardiology"])
_concept("Fundamental Neurology", ["Neurology (fundamental)"], ["Neurology"], [], ["Research methods in Neurology"])
_concept("Fundamental Oncology", ["Oncology (fundamental)"], ["Oncology"], [], ["Research methods in Oncology"])
_concept("Fundamental Psychiatry", ["Psychiatry (fundamental)"], ["Psychiatry"], [], ["Research methods in Psychiatry"])
_concept("Fundamental Dermatology", ["Dermatology (fundamental)"], ["Dermatology"], [], ["Research methods in Dermatology"])
_concept("Fundamental Epidemiology", ["Epidemiology (fundamental)"], ["Epidemiology"], [], ["Research methods in Epidemiology"])
_concept("Fundamental Toxicology", ["Toxicology (fundamental)"], ["Toxicology"], [], ["Research methods in Toxicology"])
_concept("Fundamental Biotechnology", ["Biotechnology (fundamental)"], ["Biotechnology"], [], ["Research methods in Biotechnology"])
_concept("Fundamental Bioinformatics", ["Bioinformatics (fundamental)"], ["Bioinformatics"], [], ["Research methods in Bioinformatics"])
_concept("Fundamental Genomics", ["Genomics (fundamental)"], ["Genomics"], [], ["Research methods in Genomics"])
_concept("Fundamental Proteomics", ["Proteomics (fundamental)"], ["Proteomics"], [], ["Research methods in Proteomics"])
_concept("Fundamental Bioengineering", ["Bioengineering (fundamental)"], ["Bioengineering"], [], ["Research methods in Bioengineering"])
_concept("Fundamental Biomechanics", ["Biomechanics (fundamental)"], ["Biomechanics"], [], ["Research methods in Biomechanics"])
_concept("Modern Astrophysics", ["Astrophysics (modern)"], ["Astrophysics"], [], ["Research methods in Astrophysics"])
_concept("Modern Biochemistry", ["Biochemistry (modern)"], ["Biochemistry"], [], ["Research methods in Biochemistry"])
_concept("Modern Microbiology", ["Microbiology (modern)"], ["Microbiology"], [], ["Research methods in Microbiology"])
_concept("Modern Ecology", ["Ecology (modern)"], ["Ecology"], [], ["Research methods in Ecology"])
_concept("Modern Genetics", ["Genetics (modern)"], ["Genetics"], [], ["Research methods in Genetics"])
_concept("Modern Macroeconomics", ["Macroeconomics (modern)"], ["Macroeconomics"], [], ["Research methods in Macroeconomics"])
_concept("Modern Microeconomics", ["Microeconomics (modern)"], ["Microeconomics"], [], ["Research methods in Microeconomics"])
_concept("Modern Econometrics", ["Econometrics (modern)"], ["Econometrics"], [], ["Research methods in Econometrics"])
_concept("Modern Jurisprudence", ["Jurisprudence (modern)"], ["Jurisprudence"], [], ["Research methods in Jurisprudence"])
_concept("Modern Sociology", ["Sociology (modern)"], ["Sociology"], [], ["Research methods in Sociology"])
_concept("Modern Psychology", ["Psychology (modern)"], ["Psychology"], [], ["Research methods in Psychology"])
_concept("Modern Neuroscience", ["Neuroscience (modern)"], ["Neuroscience"], [], ["Research methods in Neuroscience"])
_concept("Modern Linguistics", ["Linguistics (modern)"], ["Linguistics"], [], ["Research methods in Linguistics"])
_concept("Modern Pedagogy", ["Pedagogy (modern)"], ["Pedagogy"], [], ["Research methods in Pedagogy"])
_concept("Modern Anthropology", ["Anthropology (modern)"], ["Anthropology"], [], ["Research methods in Anthropology"])
_concept("Modern Archaeology", ["Archaeology (modern)"], ["Archaeology"], [], ["Research methods in Archaeology"])
_concept("Modern Musicology", ["Musicology (modern)"], ["Musicology"], [], ["Research methods in Musicology"])
_concept("Modern Cartography", ["Cartography (modern)"], ["Cartography"], [], ["Research methods in Cartography"])
_concept("Modern Biophysics", ["Biophysics (modern)"], ["Biophysics"], [], ["Research methods in Biophysics"])
_concept("Modern Nanotechnology", ["Nanotechnology (modern)"], ["Nanotechnology"], [], ["Research methods in Nanotechnology"])
_concept("Modern Organic Chemistry", ["Organic Chemistry (modern)"], ["Organic Chemistry"], [], ["Research methods in Organic Chemistry"])
_concept("Modern Inorganic Chemistry", ["Inorganic Chemistry (modern)"], ["Inorganic Chemistry"], [], ["Research methods in Inorganic Chemistry"])
_concept("Modern Geophysics", ["Geophysics (modern)"], ["Geophysics"], [], ["Research methods in Geophysics"])
_concept("Modern Meteorology", ["Meteorology (modern)"], ["Meteorology"], [], ["Research methods in Meteorology"])
_concept("Modern Oceanography", ["Oceanography (modern)"], ["Oceanography"], [], ["Research methods in Oceanography"])
_concept("Modern Immunology", ["Immunology (modern)"], ["Immunology"], [], ["Research methods in Immunology"])
_concept("Modern Pharmacology", ["Pharmacology (modern)"], ["Pharmacology"], [], ["Research methods in Pharmacology"])
_concept("Modern Pathology", ["Pathology (modern)"], ["Pathology"], [], ["Research methods in Pathology"])
_concept("Modern Virology", ["Virology (modern)"], ["Virology"], [], ["Research methods in Virology"])
_concept("Modern Cytology", ["Cytology (modern)"], ["Cytology"], [], ["Research methods in Cytology"])
_concept("Modern Histology", ["Histology (modern)"], ["Histology"], [], ["Research methods in Histology"])
_concept("Modern Morphology", ["Morphology (modern)"], ["Morphology"], [], ["Research methods in Morphology"])
_concept("Modern Taxonomy", ["Taxonomy (modern)"], ["Taxonomy"], [], ["Research methods in Taxonomy"])
_concept("Modern Physiology", ["Physiology (modern)"], ["Physiology"], [], ["Research methods in Physiology"])
_concept("Modern Endocrinology", ["Endocrinology (modern)"], ["Endocrinology"], [], ["Research methods in Endocrinology"])
_concept("Modern Cardiology", ["Cardiology (modern)"], ["Cardiology"], [], ["Research methods in Cardiology"])
_concept("Modern Neurology", ["Neurology (modern)"], ["Neurology"], [], ["Research methods in Neurology"])
_concept("Modern Oncology", ["Oncology (modern)"], ["Oncology"], [], ["Research methods in Oncology"])
_concept("Modern Psychiatry", ["Psychiatry (modern)"], ["Psychiatry"], [], ["Research methods in Psychiatry"])
_concept("Modern Dermatology", ["Dermatology (modern)"], ["Dermatology"], [], ["Research methods in Dermatology"])
_concept("Modern Epidemiology", ["Epidemiology (modern)"], ["Epidemiology"], [], ["Research methods in Epidemiology"])
_concept("Modern Toxicology", ["Toxicology (modern)"], ["Toxicology"], [], ["Research methods in Toxicology"])
_concept("Modern Biotechnology", ["Biotechnology (modern)"], ["Biotechnology"], [], ["Research methods in Biotechnology"])
_concept("Modern Bioinformatics", ["Bioinformatics (modern)"], ["Bioinformatics"], [], ["Research methods in Bioinformatics"])
_concept("Modern Genomics", ["Genomics (modern)"], ["Genomics"], [], ["Research methods in Genomics"])
_concept("Modern Proteomics", ["Proteomics (modern)"], ["Proteomics"], [], ["Research methods in Proteomics"])
_concept("Modern Bioengineering", ["Bioengineering (modern)"], ["Bioengineering"], [], ["Research methods in Bioengineering"])
_concept("Modern Biomechanics", ["Biomechanics (modern)"], ["Biomechanics"], [], ["Research methods in Biomechanics"])
_concept("Comparative Astrophysics", ["Astrophysics (comparative)"], ["Astrophysics"], [], ["Research methods in Astrophysics"])
_concept("Comparative Biochemistry", ["Biochemistry (comparative)"], ["Biochemistry"], [], ["Research methods in Biochemistry"])
_concept("Comparative Microbiology", ["Microbiology (comparative)"], ["Microbiology"], [], ["Research methods in Microbiology"])
_concept("Comparative Ecology", ["Ecology (comparative)"], ["Ecology"], [], ["Research methods in Ecology"])
_concept("Comparative Genetics", ["Genetics (comparative)"], ["Genetics"], [], ["Research methods in Genetics"])
_concept("Comparative Macroeconomics", ["Macroeconomics (comparative)"], ["Macroeconomics"], [], ["Research methods in Macroeconomics"])
_concept("Comparative Microeconomics", ["Microeconomics (comparative)"], ["Microeconomics"], [], ["Research methods in Microeconomics"])
_concept("Comparative Econometrics", ["Econometrics (comparative)"], ["Econometrics"], [], ["Research methods in Econometrics"])
_concept("Comparative Jurisprudence", ["Jurisprudence (comparative)"], ["Jurisprudence"], [], ["Research methods in Jurisprudence"])
_concept("Comparative Sociology", ["Sociology (comparative)"], ["Sociology"], [], ["Research methods in Sociology"])
_concept("Comparative Psychology", ["Psychology (comparative)"], ["Psychology"], [], ["Research methods in Psychology"])
_concept("Comparative Neuroscience", ["Neuroscience (comparative)"], ["Neuroscience"], [], ["Research methods in Neuroscience"])
_concept("Comparative Linguistics", ["Linguistics (comparative)"], ["Linguistics"], [], ["Research methods in Linguistics"])
_concept("Comparative Pedagogy", ["Pedagogy (comparative)"], ["Pedagogy"], [], ["Research methods in Pedagogy"])
_concept("Comparative Anthropology", ["Anthropology (comparative)"], ["Anthropology"], [], ["Research methods in Anthropology"])
_concept("Comparative Archaeology", ["Archaeology (comparative)"], ["Archaeology"], [], ["Research methods in Archaeology"])
_concept("Comparative Musicology", ["Musicology (comparative)"], ["Musicology"], [], ["Research methods in Musicology"])
_concept("Comparative Cartography", ["Cartography (comparative)"], ["Cartography"], [], ["Research methods in Cartography"])
_concept("Comparative Biophysics", ["Biophysics (comparative)"], ["Biophysics"], [], ["Research methods in Biophysics"])
_concept("Comparative Nanotechnology", ["Nanotechnology (comparative)"], ["Nanotechnology"], [], ["Research methods in Nanotechnology"])
_concept("Comparative Organic Chemistry", ["Organic Chemistry (comparative)"], ["Organic Chemistry"], [], ["Research methods in Organic Chemistry"])
_concept("Comparative Inorganic Chemistry", ["Inorganic Chemistry (comparative)"], ["Inorganic Chemistry"], [], ["Research methods in Inorganic Chemistry"])
_concept("Comparative Geophysics", ["Geophysics (comparative)"], ["Geophysics"], [], ["Research methods in Geophysics"])
_concept("Comparative Meteorology", ["Meteorology (comparative)"], ["Meteorology"], [], ["Research methods in Meteorology"])
_concept("Comparative Oceanography", ["Oceanography (comparative)"], ["Oceanography"], [], ["Research methods in Oceanography"])
_concept("Comparative Immunology", ["Immunology (comparative)"], ["Immunology"], [], ["Research methods in Immunology"])
_concept("Comparative Pharmacology", ["Pharmacology (comparative)"], ["Pharmacology"], [], ["Research methods in Pharmacology"])
_concept("Comparative Pathology", ["Pathology (comparative)"], ["Pathology"], [], ["Research methods in Pathology"])
_concept("Comparative Virology", ["Virology (comparative)"], ["Virology"], [], ["Research methods in Virology"])
_concept("Comparative Cytology", ["Cytology (comparative)"], ["Cytology"], [], ["Research methods in Cytology"])
_concept("Comparative Histology", ["Histology (comparative)"], ["Histology"], [], ["Research methods in Histology"])
_concept("Comparative Morphology", ["Morphology (comparative)"], ["Morphology"], [], ["Research methods in Morphology"])
_concept("Comparative Taxonomy", ["Taxonomy (comparative)"], ["Taxonomy"], [], ["Research methods in Taxonomy"])
_concept("Comparative Physiology", ["Physiology (comparative)"], ["Physiology"], [], ["Research methods in Physiology"])
_concept("Comparative Endocrinology", ["Endocrinology (comparative)"], ["Endocrinology"], [], ["Research methods in Endocrinology"])
_concept("Comparative Cardiology", ["Cardiology (comparative)"], ["Cardiology"], [], ["Research methods in Cardiology"])
_concept("Comparative Neurology", ["Neurology (comparative)"], ["Neurology"], [], ["Research methods in Neurology"])
_concept("Comparative Oncology", ["Oncology (comparative)"], ["Oncology"], [], ["Research methods in Oncology"])
_concept("Comparative Psychiatry", ["Psychiatry (comparative)"], ["Psychiatry"], [], ["Research methods in Psychiatry"])
_concept("Comparative Dermatology", ["Dermatology (comparative)"], ["Dermatology"], [], ["Research methods in Dermatology"])
_concept("Comparative Epidemiology", ["Epidemiology (comparative)"], ["Epidemiology"], [], ["Research methods in Epidemiology"])
_concept("Comparative Toxicology", ["Toxicology (comparative)"], ["Toxicology"], [], ["Research methods in Toxicology"])
_concept("Comparative Biotechnology", ["Biotechnology (comparative)"], ["Biotechnology"], [], ["Research methods in Biotechnology"])
_concept("Comparative Bioinformatics", ["Bioinformatics (comparative)"], ["Bioinformatics"], [], ["Research methods in Bioinformatics"])
_concept("Comparative Genomics", ["Genomics (comparative)"], ["Genomics"], [], ["Research methods in Genomics"])
_concept("Comparative Proteomics", ["Proteomics (comparative)"], ["Proteomics"], [], ["Research methods in Proteomics"])
_concept("Comparative Bioengineering", ["Bioengineering (comparative)"], ["Bioengineering"], [], ["Research methods in Bioengineering"])
_concept("Comparative Biomechanics", ["Biomechanics (comparative)"], ["Biomechanics"], [], ["Research methods in Biomechanics"])
_concept("Empirical Astrophysics", ["Astrophysics (empirical)"], ["Astrophysics"], [], ["Research methods in Astrophysics"])
_concept("Empirical Biochemistry", ["Biochemistry (empirical)"], ["Biochemistry"], [], ["Research methods in Biochemistry"])
_concept("Empirical Microbiology", ["Microbiology (empirical)"], ["Microbiology"], [], ["Research methods in Microbiology"])
_concept("Empirical Ecology", ["Ecology (empirical)"], ["Ecology"], [], ["Research methods in Ecology"])
_concept("Empirical Genetics", ["Genetics (empirical)"], ["Genetics"], [], ["Research methods in Genetics"])
_concept("Empirical Macroeconomics", ["Macroeconomics (empirical)"], ["Macroeconomics"], [], ["Research methods in Macroeconomics"])
_concept("Empirical Microeconomics", ["Microeconomics (empirical)"], ["Microeconomics"], [], ["Research methods in Microeconomics"])
_concept("Empirical Econometrics", ["Econometrics (empirical)"], ["Econometrics"], [], ["Research methods in Econometrics"])
_concept("Empirical Jurisprudence", ["Jurisprudence (empirical)"], ["Jurisprudence"], [], ["Research methods in Jurisprudence"])
_concept("Empirical Sociology", ["Sociology (empirical)"], ["Sociology"], [], ["Research methods in Sociology"])
_concept("Empirical Psychology", ["Psychology (empirical)"], ["Psychology"], [], ["Research methods in Psychology"])
_concept("Empirical Neuroscience", ["Neuroscience (empirical)"], ["Neuroscience"], [], ["Research methods in Neuroscience"])
_concept("Empirical Linguistics", ["Linguistics (empirical)"], ["Linguistics"], [], ["Research methods in Linguistics"])
_concept("Empirical Pedagogy", ["Pedagogy (empirical)"], ["Pedagogy"], [], ["Research methods in Pedagogy"])
_concept("Empirical Anthropology", ["Anthropology (empirical)"], ["Anthropology"], [], ["Research methods in Anthropology"])
_concept("Empirical Archaeology", ["Archaeology (empirical)"], ["Archaeology"], [], ["Research methods in Archaeology"])
_concept("Empirical Musicology", ["Musicology (empirical)"], ["Musicology"], [], ["Research methods in Musicology"])
_concept("Empirical Cartography", ["Cartography (empirical)"], ["Cartography"], [], ["Research methods in Cartography"])
_concept("Empirical Biophysics", ["Biophysics (empirical)"], ["Biophysics"], [], ["Research methods in Biophysics"])
_concept("Empirical Nanotechnology", ["Nanotechnology (empirical)"], ["Nanotechnology"], [], ["Research methods in Nanotechnology"])
_concept("Empirical Organic Chemistry", ["Organic Chemistry (empirical)"], ["Organic Chemistry"], [], ["Research methods in Organic Chemistry"])
_concept("Empirical Inorganic Chemistry", ["Inorganic Chemistry (empirical)"], ["Inorganic Chemistry"], [], ["Research methods in Inorganic Chemistry"])
_concept("Empirical Geophysics", ["Geophysics (empirical)"], ["Geophysics"], [], ["Research methods in Geophysics"])
_concept("Empirical Meteorology", ["Meteorology (empirical)"], ["Meteorology"], [], ["Research methods in Meteorology"])
_concept("Empirical Oceanography", ["Oceanography (empirical)"], ["Oceanography"], [], ["Research methods in Oceanography"])
_concept("Empirical Immunology", ["Immunology (empirical)"], ["Immunology"], [], ["Research methods in Immunology"])
_concept("Empirical Pharmacology", ["Pharmacology (empirical)"], ["Pharmacology"], [], ["Research methods in Pharmacology"])
_concept("Empirical Pathology", ["Pathology (empirical)"], ["Pathology"], [], ["Research methods in Pathology"])
_concept("Empirical Virology", ["Virology (empirical)"], ["Virology"], [], ["Research methods in Virology"])
_concept("Empirical Cytology", ["Cytology (empirical)"], ["Cytology"], [], ["Research methods in Cytology"])
_concept("Empirical Histology", ["Histology (empirical)"], ["Histology"], [], ["Research methods in Histology"])
_concept("Empirical Morphology", ["Morphology (empirical)"], ["Morphology"], [], ["Research methods in Morphology"])
_concept("Empirical Taxonomy", ["Taxonomy (empirical)"], ["Taxonomy"], [], ["Research methods in Taxonomy"])
_concept("Empirical Physiology", ["Physiology (empirical)"], ["Physiology"], [], ["Research methods in Physiology"])
_concept("Empirical Endocrinology", ["Endocrinology (empirical)"], ["Endocrinology"], [], ["Research methods in Endocrinology"])
_concept("Empirical Cardiology", ["Cardiology (empirical)"], ["Cardiology"], [], ["Research methods in Cardiology"])
_concept("Empirical Neurology", ["Neurology (empirical)"], ["Neurology"], [], ["Research methods in Neurology"])
_concept("Empirical Oncology", ["Oncology (empirical)"], ["Oncology"], [], ["Research methods in Oncology"])
_concept("Empirical Psychiatry", ["Psychiatry (empirical)"], ["Psychiatry"], [], ["Research methods in Psychiatry"])
_concept("Empirical Dermatology", ["Dermatology (empirical)"], ["Dermatology"], [], ["Research methods in Dermatology"])
_concept("Empirical Epidemiology", ["Epidemiology (empirical)"], ["Epidemiology"], [], ["Research methods in Epidemiology"])
_concept("Empirical Toxicology", ["Toxicology (empirical)"], ["Toxicology"], [], ["Research methods in Toxicology"])
_concept("Empirical Biotechnology", ["Biotechnology (empirical)"], ["Biotechnology"], [], ["Research methods in Biotechnology"])
_concept("Empirical Bioinformatics", ["Bioinformatics (empirical)"], ["Bioinformatics"], [], ["Research methods in Bioinformatics"])
_concept("Empirical Genomics", ["Genomics (empirical)"], ["Genomics"], [], ["Research methods in Genomics"])
_concept("Empirical Proteomics", ["Proteomics (empirical)"], ["Proteomics"], [], ["Research methods in Proteomics"])
_concept("Empirical Bioengineering", ["Bioengineering (empirical)"], ["Bioengineering"], [], ["Research methods in Bioengineering"])
_concept("Empirical Biomechanics", ["Biomechanics (empirical)"], ["Biomechanics"], [], ["Research methods in Biomechanics"])

def expand_thesaurus_query(term: str) -> Set[str]:
    clean = term.strip().lower()
    expanded = {clean}
    if clean in THESAURUS_GRAPH:
        c = THESAURUS_GRAPH[clean]
        expanded.update(a.lower() for a in c.alternate_labels)
        expanded.update(n.lower() for n in c.narrower_concepts)
        expanded.update(r.lower() for r in c.related_concepts)
    return expanded
