"""Z39.50 ASN.1 Tags, PDU Identifiers, and Bib-1 Attribute Architecture."""

# ASN.1 Universal Tags
ASN1_TAG_BOOLEAN = 0x01
ASN1_TAG_INTEGER = 0x02
ASN1_TAG_BIT_STRING = 0x03
ASN1_TAG_OCTET_STRING = 0x04
ASN1_TAG_NULL = 0x05
ASN1_TAG_OBJECT_IDENTIFIER = 0x06
ASN1_TAG_ENUMERATED = 0x0a
ASN1_TAG_SEQUENCE = 0x10
ASN1_TAG_SET = 0x11
ASN1_TAG_VISIBLE_STRING = 0x1a
ASN1_TAG_GENERALIZED_TIME = 0x18

# Z39.50 PDU Context-Specific Choice Tags
PDU_INIT_REQUEST = 20
PDU_INIT_RESPONSE = 21
PDU_SEARCH_REQUEST = 22
PDU_SEARCH_RESPONSE = 23
PDU_PRESENT_REQUEST = 24
PDU_PRESENT_RESPONSE = 25
PDU_DELETE_RESULT_SET_REQUEST = 26
PDU_DELETE_RESULT_SET_RESPONSE = 27
PDU_RESOURCE_CONTROL_REQUEST = 28
PDU_RESOURCE_CONTROL_RESPONSE = 29
PDU_TRIGGER_RESOURCE_CONTROL_REQUEST = 30
PDU_ACCESS_CONTROL_REQUEST = 35
PDU_ACCESS_CONTROL_RESPONSE = 36
PDU_CLOSE = 44

# Bib-1 Attribute Types
BIB1_ATTR_USE = 1
BIB1_ATTR_RELATION = 2
BIB1_ATTR_POSITION = 3
BIB1_ATTR_STRUCTURE = 4
BIB1_ATTR_TRUNCATION = 5
BIB1_ATTR_COMPLETENESS = 6

# Bib-1 Use Attributes (Common Standard Codes)
BIB1_USE_ANY = 1016
BIB1_USE_TITLE = 4
BIB1_USE_TITLE_SERIES = 5
BIB1_USE_AUTHOR = 1003
BIB1_USE_AUTHOR_PERSONAL = 1
BIB1_USE_AUTHOR_CORPORATE = 2
BIB1_USE_ISBN = 7
BIB1_USE_ISSN = 8
BIB1_USE_LCCN = 9
BIB1_USE_SUBJECT = 21
BIB1_USE_DATE_PUBLICATION = 31
BIB1_USE_KEYWORD = 1011
BIB1_USE_BARCODE = 1018

# Bib-1 Relation Attributes
BIB1_REL_LESS_THAN = 1
BIB1_REL_LESS_THAN_OR_EQUAL = 2
BIB1_REL_EQUAL = 3
BIB1_REL_GREATER_OR_EQUAL = 4
BIB1_REL_GREATER_THAN = 5
BIB1_REL_NOT_EQUAL = 6

# Standard Z39.50 Diagnostic Codes
DIAG_PERMANENT_SYSTEM_ERROR = 1
DIAG_TEMPORARY_SYSTEM_ERROR = 2
DIAG_UNSUPPORTED_SEARCH = 107
DIAG_DATABASE_UNAVAILABLE = 109
DIAG_SPECIFIED_RESULT_SET_EXISTS = 113
DIAG_RESULT_SET_DOES_NOT_EXIST = 114
